### Intro Packages

In [5]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 500)

# Datasets inspection

In [2]:
df_acquisitions = pd.read_csv('cb_acquisitions.csv')
df_acquisitions.head(3)

,id,acquisition_id,acquiring_object_id,acquired_object_id,term_code,price_amount,price_currency_code,acquired_at,source_url,source_description,created_at,updated_at
0,1,1,c:11,c:10,NaN,20000000.0,USD,2007-05-30,http://venturebeat.com/2007/05/30/fox-interact...,Fox Interactive confirms purchase of Photobuck...,2007-05-31 22:19:54,2008-05-21 19:23:44
1,2,7,c:59,c:72,cash,60000000.0,USD,2007-07-01,http://www.techcrunch.com/2007/07/02/deal-is-c...,Deal is Confirmed: Google Acquired GrandCentral,2007-07-03 08:14:50,2011-05-06 21:51:05
2,3,8,c:24,c:132,cash,280000000.0,USD,2007-05-01,http://www.techcrunch.com/2007/05/30/cbs-acqui...,CBS Acquires Europe’s Last.fm for $280 million,2007-07-12 04:19:24,2008-05-19 04:48:50

In [3]:
df_degrees = pd.read_csv('cb_degrees.csv')
df_degrees.head(3)

,id,object_id,degree_type,subject,institution,graduated_at,created_at,updated_at
0,1,p:6117,MBA,NaN,NaN,NaN,2008-02-19 03:17:36,2008-02-19 03:17:36
1,2,p:6136,BA,"English, French","Washington University, St. Louis",1990-01-01,2008-02-19 17:58:31,2008-02-25 00:23:55
2,3,p:6136,MS,Mass Communication,Boston University,1992-01-01,2008-02-19 17:58:31,2008-02-25 00:23:55

In [61]:
df_funding = pd.read_csv('cb_funding_rounds.csv', low_memory=False)
df_funding.columns

Index(['id', 'funding_round_id', 'object_id', 'funded_at',
       'funding_round_type', 'funding_round_code', 'raised_amount_usd',
       'raised_amount', 'raised_currency_code', 'pre_money_valuation_usd',
       'pre_money_valuation', 'pre_money_currency_code',
       'post_money_valuation_usd', 'post_money_valuation',
       'post_money_currency_code', 'participants', 'is_first_round',
       'is_last_round', 'source_url', 'source_description', 'created_by',
       'created_at', 'updated_at'],
      dtype='object')

In [6]:
df_relations = pd.read_csv('cb_relationships.csv', low_memory=False)
df_relations.head(50)

,id,relationship_id,person_object_id,relationship_object_id,start_at,end_at,is_past,sequence,title,created_at,updated_at
0,1,1,p:2,c:1,NaN,NaN,0,8,Co-Founder/CEO/Board of Directors,2007-05-25 07:03:54,2013-06-03 09:58:46
1,2,2,p:3,c:1,NaN,NaN,1,279242,VP Marketing,2007-05-25 07:04:16,2010-05-21 16:31:34
2,3,3,p:4,c:3,NaN,NaN,0,4,Evangelist,2007-05-25 19:33:03,2013-06-29 13:36:58
3,4,4,p:5,c:3,2006-03-01,2009-12-01,1,4,Senior Director Strategic Alliances,2007-05-25 19:34:53,2013-06-29 10:25:34
4,6,6,p:7,c:4,2005-07-01,2010-04-05,1,1,Chief Executive Officer,2007-05-25 20:05:33,2010-04-05 18:41:41
5,7,7,p:8,c:4,NaN,NaN,1,1,Senior Software Engineer,2007-05-25 20:06:45,2010-01-12 01:13:29
6,8,8,p:9,c:4,NaN,NaN,1,1,Systems Engineering Manager,2007-05-25 20:07:50,2010-08-03 22:00:58
7,9,9,p:10,c:5,NaN,NaN,0,1,"Founder and CEO, Board Of Directors",2007-05-25 21:51:46,2010-01-25 21:49:44
8,10,10,p:11,c:5,NaN,NaN,1,1,Co-Founder,2007-05-25 22:15:05,2011-08-11 23:48:45
9,11,11,p:12,c:5,NaN,NaN,1,3,"Chief Revenue Officer, VP of Operations",2007-05-25 22:15:59,2010-01-25 21:49:45
10,12,12,p:13,c:5,NaN,NaN,1,1,VP of Product Management,2007-05-25 22:16:59,2010-01-25 21:49:45
11,13,13,p:14,c:5,1993-07-04,1982-02-28,1,1,Co-founder,2007-05-25 22:17:27,2010-09-01 18:15:45
12,14,14,p:16,c:7299,NaN,NaN,1,2,Founder and CEO,2007-05-26 12:44:52,2011-07-19 00:05:01
13,15,15,p:17,c:7299,NaN,NaN,1,2,Co-founder and CTO,2007-05-26 12:45:46,2011-07-19 00:05:01
14,16,16,p:18,c:7299,2005-09-01,2009-10-01,1,1,"SVP, Technology and Partnerships",2007-05-26 12:47:13,2011-07-19 00:05:01
15,17,17,p:19,c:7299,2006-08-01,2009-08-01,1,8,"VP, Finance & Administration",2007-05-26 12:47:49,2011-10-28 03:08:15
16,18,18,p:20,c:7299,NaN,NaN,0,1,"VP, Sales",2007-05-26 12:48:20,2011-07-19 00:05:01
17,19,19,p:21,c:7299,NaN,NaN,0,1,"VP, Customer Service",2007-05-26 12:49:23,2011-07-19 00:05:01
18,20,20,p:22,c:7299,2005-10-01,2008-03-01,1,1,"VP, Business Development",2007-05-26 12:49:45,2013-08-07 08:51:20
19,21,21,p:23,c:7299,NaN,NaN,1,1,"VP, Engineering",2007-05-26 12:50:11,2011-07-19 00:05:02
20,22,22,p:24,c:7299,2007-01-01,2009-07-01,1,8,"VP, Marketing",2007-05-26 12:51:13,2013-11-12 23:51:51
21,23,23,p:25,c:7299,NaN,NaN,0,1,"VP, Product",2007-05-26 12:51:42,2011-07-19 00:05:02
22,25,25,p:29,f:3,1996-05-01,NaN,0,10,General Partner,2007-05-30 18:23:49,2013-08-12 04:05:45
23,27,27,p:30,c:9,2006-06-01,2009-07-01,1,279251,Founder & Chairman,2007-05-31 19:56:06,2013-06-27 04:29:57
24,28,28,p:31,c:9,NaN,NaN,0,3,Board Member,2007-05-31 19:57:11,2010-01-10 22:15:00
25,29,29,p:26,f:6,NaN,NaN,0,6,Partner,2007-05-31 20:15:01,2012-03-13 23:08:47
26,30,30,p:32,f:6,NaN,NaN,0,5,Partner,2007-05-31 20:15:31,2012-03-13 23:08:47
27,31,31,p:33,f:6,NaN,NaN,0,5,Partner,2007-05-31 20:16:11,2012-03-13 23:08:47
28,32,32,p:34,f:6,NaN,NaN,0,5,Executive General Partner,2007-05-31 20:16:40,2012-03-13 23:08:47
29,33,33,p:35,f:7,NaN,NaN,0,7,General Partner,2007-05-31 20:32:21,2013-08-26 20:19:07
30,34,34,p:35,c:9,NaN,NaN,1,2,Board Member,2007-05-31 20:49:24,2013-11-20 19:21:41
31,35,35,p:26,c:9,NaN,NaN,0,7,Board of Directors,2007-05-31 20:49:38,2013-12-02 08:28:05
32,38,38,p:37,f:7,2000-03-01,2002-03-01,1,2,Partner,2007-11-12 12:39:14,2013-07-05 06:25:03
33,40,40,p:39,c:10,2006-05-01,2008-03-01,1,2,Co-founder and CEO,2007-05-31 21:28:58,2010-11-19 19:13:15
34,41,41,p:40,c:10,NaN,NaN,1,2,Co-founder and CTO,2007-05-31 21:29:26,2010-10-18 21:21:44
35,42,42,p:41,c:10,2006-05-15,2008-07-01,1,6,"COO, Co-Founder",2007-05-31 21:30:32,2010-10-21 12:42:48
36,44,44,p:43,c:13,2012-05-01,NaN,0,5,Co-Founder & Chairman,2007-06-01 09:42:23,2013-05-02 22:46:12
37,47,47,p:46,c:12,NaN,NaN,1,2,"CEO, Co-Founder",2007-06-01 12:46:44,2010-01-27 00:32:09
38,49,49,p:48,c:12,NaN,NaN,1,1,"Director, Program Management",2007-06-01 18:54:38,2010-06-08 23:49:06
39,50,50,p:49,c:12,2006-04-01,NaN,0,6,Co-founder,2007-06-01 18:55:41,2013-07-05 04:10:34
40,52,52,p:51,c:14,NaN,NaN,0,1,Director of Strategic Relations,2007-06-01 19:38:27,2008-07-10 00:17:24
41,53,53,p:52,c:14,NaN,NaN,0,1,Chief Technology Officer,2007-06-01 19:53:54,2008-04-13 18:34:46
42,54,54,p:53,c:14,NaN,NaN,1,2,Vice President Products Strategy,2007-06-01 19:54:23,2012-12-27 00:32:56
43,57,57,p:56,c:14,NaN,NaN,0,1,Board,2007-06-01 19:56:33,2008-04-13 18:34:47
44,58,58,p:57,c:14,NaN,NaN,0,1,Board,2007-06-01 19:56:53,2008-04-13 18:34:47
45,59,59,p:58,c:14,NaN,NaN,0,2,Board,2007-06-01 19:57:16,2008-04-13 18:34:47
46,60,60,p:59,c:16,NaN,NaN,1,1,Board,2007-06-04 08:45:41,2013-03-08 21:27:10
47,61,61,p:60,c:16,2006-05-01,NaN,0,5,President & CEO,2007-06-04 08:46:11,2013-07-22 03:25:47
48,62,62,p:61,c:16,2012-06-01,2013-02-01,1,5,SVP Product Marketing & Content Programming,2007-06-04 08:46:37,2013-07-22 04:09:36
49,63,63,p:62,c:15,NaN,NaN,0,3,CEO/Co-Founder,2007-06-05 07:16:26,2011-08-10 00:02:44

In [6]:
df_funds= pd.read_csv('cb_funds.csv', low_memory=False)
df_funds.head(3)

,id,fund_id,object_id,name,funded_at,raised_amount,raised_currency_code,source_url,source_description,created_at,updated_at
0,1,1,f:371,Second Fund,2008-12-16,300000000.0,USD,http://www.pehub.com/26194/dfj-dragon-raising-...,peHub,2008-12-17 03:07:16,2008-12-17 03:07:16
1,4,4,f:17,Sequoia Israel Fourth Fund,2008-12-17,200750000.0,USD,http://www.pehub.com/26725/sequoia-israel-rais...,Sequoia Israel Raises Fourth Fund,2008-12-18 22:04:42,2008-12-18 22:04:42
2,5,5,f:951,Tenth fund,2008-08-11,650000000.0,USD,http://venturebeat.com/2008/08/11/interwest-cl...,Venture Beat,2008-12-31 09:47:51,2008-12-31 09:47:51

In [8]:
df_investments= pd.read_csv('cb_investments.csv')
df_investments.head(3)

,id,funding_round_id,funded_object_id,investor_object_id,created_at,updated_at
0,1,1,c:4,f:1,2007-07-04 04:52:57,2008-02-27 23:14:29
1,2,1,c:4,f:2,2007-07-04 04:52:57,2008-02-27 23:14:29
2,3,3,c:5,f:4,2007-05-27 06:09:10,2013-06-28 20:07:23

In [8]:
df_ipos= pd.read_csv('cb_ipos.csv')
df_ipos.head(3)

,id,ipo_id,object_id,valuation_amount,valuation_currency_code,raised_amount,raised_currency_code,public_at,stock_symbol,source_url,source_description,created_at,updated_at
0,1,1,c:1654,NaN,USD,NaN,USD,1980-12-19,NASDAQ:AAPL,NaN,NaN,2008-02-09 05:17:45,2012-04-12 04:02:59
1,2,2,c:1242,NaN,USD,NaN,NaN,1986-03-13,NASDAQ:MSFT,NaN,NaN,2008-02-09 05:25:18,2010-12-11 12:39:46
2,3,3,c:342,NaN,USD,NaN,NaN,1969-06-09,NYSE:DIS,NaN,NaN,2008-02-09 05:40:32,2010-12-23 08:58:16

In [9]:
df_milestones= pd.read_csv('cb_milestones.csv')
df_milestones.head(3)

,id,object_id,milestone_at,milestone_code,description,source_url,source_description,created_at,updated_at
0,1,c:12,2008-06-09,other,Survives iPhone 3G Stevenote,http://www.techcrunch.com/2008/06/10/twitter-f...,"Twitter Fails To Fail, Community Rejoices",2008-06-18 08:14:06,2008-06-18 08:14:06
1,2,c:3138,2008-06-17,other,Twhirl announces support for Seesmic video pla...,http://www.inquisitr.com/1103/seesmic-now-avai...,Seesmic Now Available In Twhirl,2008-06-18 08:46:28,2008-06-18 08:46:28
2,3,c:59,2008-06-18,other,More than 4 Billion videos viewed at Google Si...,http://www.comscore.com/press/release.asp?pres...,11 Billion Videos Viewed Online in the U.S. in...,2008-06-18 08:50:24,2008-06-18 08:50:24

In [7]:
df_objects= pd.read_csv('cb_objects.csv', low_memory=False)
df_objects

,id,entity_type,entity_id,parent_id,name,normalized_name,permalink,category_code,status,founded_at,closed_at,domain,homepage_url,twitter_username,logo_url,logo_width,logo_height,short_description,description,overview,tag_list,country_code,state_code,city,region,first_investment_at,last_investment_at,investment_rounds,invested_companies,first_funding_at,last_funding_at,funding_rounds,funding_total_usd,first_milestone_at,last_milestone_at,milestones,relationships,created_by,created_at,updated_at
0,c:1,Company,1,NaN,Wetpaint,wetpaint,/company/wetpaint,web,operating,2005-10-17,NaN,wetpaint-inc.com,http://wetpaint-inc.com,BachelrWetpaint,http://s3.amazonaws.com/crunchbase_prod_assets...,401.0,54.0,NaN,Technology Platform Company,Wetpaint is a technology platform company that...,"wiki, seattle, elowitz, media-industry, media-...",USA,WA,Seattle,Seattle,NaN,NaN,NaN,NaN,2005-10-01,2008-05-19,3.0,39750000.0,2010-09-05,2013-09-18,5.0,17.0,initial-importer,2007-05-25 06:51:27,2013-04-13 03:29:00
1,c:10,Company,10,NaN,Flektor,flektor,/company/flektor,games_video,acquired,NaN,NaN,flektor.com,http://www.flektor.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,186.0,85.0,NaN,NaN,Flektor is a rich-media mash-up platform that ...,"flektor, photo, video",USA,CA,Culver City,Los Angeles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,initial-importer,2007-05-31 21:11:51,2008-05-23 23:23:14
2,c:100,Company,100,NaN,There,there,/company/there,games_video,acquired,NaN,NaN,there.com,http://www.there.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,107.0,34.0,NaN,NaN,There.com is an online virtual world where any...,"virtualworld, there, teens",USA,CA,San Mateo,SF Bay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-02-01,2011-09-23,4.0,12.0,initial-importer,2007-08-06 23:52:45,2013-11-04 02:09:48
3,c:10000,Company,10000,NaN,MYWEBBO,mywebbo,/company/mywebbo,network_hosting,operating,2008-07-26,NaN,mywebbo.com,http://www.mywebbo.com,NaN,NaN,NaN,NaN,NaN,NaN,"BRAND NEW ONLINE SOCIAL NETWORKING WEBSITE,FOR...","social-network, new, website, web, friends, ch...",NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-08-24 16:51:57,2008-09-06 14:19:18
4,c:10001,Company,10001,NaN,THE Movie Streamer,the movie streamer,/company/the-movie-streamer,games_video,operating,2008-07-26,NaN,themoviestreamer.com,http://themoviestreamer.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,200.0,74.0,NaN,NaN,This company shows free movies online on their...,"watch, full-length, moives, online, for, free,...",NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-08-24 17:10:34,2008-09-06 14:19:18
5,c:10002,Company,10002,NaN,Synergie Media,synergie media,/company/synergie-media,advertising,operating,2007-06-27,NaN,synergie-media.com,http://www.synergie-media.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,284.0,48.0,NaN,NaN,Synergie Media is a Dutch and Moroccan Web Des...,"social-media, web-design, web-development, out...",MAR,NaN,Agadir,Agadir,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2008-08-24 17:39:10,2008-09-06 14:19:19
6,c:10003,Company,10003,NaN,Green Basti Ecosystems,green basti ecosystems,/company/green-basti-ecosystems,cleantech,operating,2008-08-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Creating infrastructure to provide incentives ...,"cleantech, alternative-energy, biogas, carbon-...",IND,NaN,Vadodara,Vadodara,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-08-24 19:49:25,2010-04-22 23:48:20
7,c:100042,Company,100042,NaN,HostNine,hostnine,/company/hostnine,NaN,operating,NaN,NaN,hostnine.com,http://www.hostnine.com,Hostnine,http://s3.amazonaws.com/crunchbase_prod_assets...,187.0,53.0,NaN,NaN,At HostNine they are commited to continually e...,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-06-20,2011-06-20,1.0,1.0,NaN,2011-09-07 00:53:17,2011-12-20 09:09:53
8,c:10005,Company,10005,NaN,Thomas Publishing,thomas publishing,/company/thomas-publishing,advertising,operating,NaN,NaN,thomaspublishing.com,http://www.thomaspublishing.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,276.0,47.0,NaN,Online Media,"For more than a century, Thomas Publishing has...",NaN,USA,NY,New York,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06-01,1999-06-01,1.0,2.0,NaN,2008-08-24 20:21:21,2009-11-19 17:21:00
9,c:100062,Company,100062,NaN,Vetter Idea Management System,vetter idea management system,/company/vetter-idea-management-system,enterprise,operating,2011-08-01,NaN,getvetter.com,http://www.getvetter.com,getvetter,http://s3.amazonaws.com/crunchbase_prod_assets...,200.0,67.0,NaN,SaaS Idea Management System,Vetter is a web-based system that helps manage...,"saas, idea-management-system, innovation",NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-08-01,2011-08-01,1.0,2.0,dmurtagh,2011-09-07 01:04:56,2011-09-24 13:13:18
10,c:100068,Company,100068,NaN,ChatRandom,chatrandom,/company/chatrandom,games_video,operating,2011-02-01,NaN,chatrandom.com,http://chatrandom.com,chatrandom,http://s3.amazonaws.com/crunchbase_prod_assets...,200.0,65.0,NaN,random video chat,ChatRandom is a new Chatroulette Alternative w...,"chatroulette, video-chat, webcam-chat, chat-rooms",NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-04-09,2012-04-09,1.0,NaN,NaN,2011-09-07 01:09:59,2011-09-12 04:14:57
11,c:10008,Company,10008,NaN,ScapadasAmorosas,scapadasamorosas,/company/scapadasamorosas,other,operating,2007-03-01,NaN,scapadasamorosas.com,http://scapadasamorosas.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,576.0,432.0,NaN,Sitio de citas para casados y casadas.,ScapadasAmorosas.com es el primer sitio de cit...,"mujer-casada-busca, hombre-casado-busca, busco...",NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-08-24 21:48:16,2013-04-02 12:36:50
12,c:10009,Company,10009,NaN,dimension5 labs,dimension5 labs,/company/dimension5-labs,advertising,operating,2008-08-01,NaN,d5labs.com,http://d5labs.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,300.0,85.0,NaN,NaN,dimension5 labs is a full service digital adve...,"virtual-worlds, advertising-agency, complex-pr...",USA,NM,Santa Fe,Santa Fe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-08-22,2008-08-22,1.0,2.0,NaN,2008-08-24 21:54:55,2008-12-21 17:21:53
13,c:1001,Company,1001,NaN,FriendFeed,friendfeed,/company/friendfeed,web,acquired,2007-10-01,NaN,friendfeed.com,http://friendfeed.com,friendfeed,http://s3.amazonaws.com/crunchbase_prod_assets...,200.0,56.0,NaN,Social network aggregator,[FriendFeed](http://www.friendfeed.com) aims t...,"socialnetwork, newsfeed, socialnetworkaggregator",USA,CA,Mountain View,SF Bay,NaN,NaN,NaN,NaN,2008-02-26,2008-02-26,1.0,5000000.0,2008-05-01,2012-09-13,3.0,14.0,initial-importer,2007-10-01 10:17:13,2013-03-13 21:44:15
14,c:10010,Company,10010,NaN,Whooligan,whooligan,/company/whooligan,games_video,operating,2007-12-01,NaN,whooligan.com,http://www.whooligan.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,150.0,54.0,NaN,NaN,Whooligan is a new global soccer lifestyle bra...,"videos, video, photo, photos, apparel, soccer,...",NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2008-08-24 22:10:04,2013-06-28 20:51:46
15,c:10011,Company,10011,NaN,PoetryVisualized.com,poetryvisualized,/company/poetryvisualized-com,games_video,operating,2008-01-01,NaN,poetryvisualized.com,http://www.poetryvisualized.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,2367.0,810.0,NaN,Poetry site,"Visual poetry, is poetry or art in which the v...","poetry, publish, audio, video, film, visual, a...",USA,CA,Julian,San Diego,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-01-01,2008-01-01,1.0,3.0,NaN,2008-08-24 22:21:46,2009-04-03 20:32:21
16,c:10012,Company,10012,NaN,moviestring.com,moviestring,/company/moviestring-com,games_video,closed,2008-08-22,2010-01-01,moviestring.com,http://moviestring.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,223.0,45.0,NaN,NaN,moviestring.com provides a place for user to c...,"movies, micro-reviews, micro-blogging",NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2008-08-24 23:07:26,2010-10-01 00:12:22
17,c:10013,Company,10013,NaN,The Adory,the adory,/company/the-adory,consulting,operating,2008-01-01,NaN,theadory.com,http://www.theadory.com,the_adory,http://s3.amazonaws.com/crunchbase_prod_assets...,300.0,89.0,NaN,Image and Brand Consulting,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2008-08-24 23:23:00,2009-04-03 18:00:41
18,c:10014,Company,10014,NaN,Mobclix,mobclix,/company/mobclix,mobile,acquired,2008-03-01,NaN,mobclix.com,http://www.mobclix.com,mobclix,http://s3.amazonaws.com/crunchbase_prod_assets...,197.0,79.0,NaN,iPhone Ad Exchange Provider,Mobclix (www.mobclix.com) is the industry's la...,"techcrunch50, tc50, iphone, analytics, free-de...",USA,CA,Palo Alto,SF Bay,NaN,NaN,NaN,NaN,2008-09-01,2008-09-01,1.0,NaN,1995-03-01,2012-09-18,4.0,9.0,NaN,2008-08-25 01:32:43,2012-09-22 03:36:21
19,c:10015,Company,10015,NaN,Fitbit,fitbit,/company/fitbit,health,operating,2007-10-01,NaN,fitbit.com,http://www.fitbit.com,fitbit,http://s3.amazonaws.com/crunchbase_prod_assets...,2228.0,793.0,"Fitbit offers compact, wireless, wearable sens...",NaN,"Fitbit inspires people to exercise more, eat b...","techcrunch50, tc50, health, hardware, fitness,...",USA,CA,San Francisco,SF Bay,NaN,NaN,NaN,NaN,2008-10-10,2013-08-13,5.0,68069200.0,NaN,NaN,NaN,14.0,NaN,2008-08-25 02:16:54,2013-12-04 09:52:42
20,c:100155,Company,100155,NaN,MTPV,mtpv,/company/mtpv,cleantech,operating,2003-01-01,NaN,mtpv.com,http://www.mtpv.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,150.0,50.0,NaN,NaN,MTPV Corporation is a clean energy company foc...,NaN,USA,TX,Austin,Austin,NaN,NaN,NaN,NaN,2011-03-08,2012-01-26,3.0,10125293.0,2010-01-01,2010-01-01,1.0,6.0,arun,2011-09-07 02:01:00,2013-04-10 04:35:04
21,c:10016,Company,10016,NaN,Camcorder-batteries.us,camcorder batteries us,/company/camcorder-batteries-us,other,operating,NaN,NaN,camcorder-batteries.us,http://www.camcorder-batteries.us,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,444.0,74.0,NaN,NaN,"Wholesale/retail Camcorder batteries, digital ...","camcorder-batteries, batteries, digital-camera...",NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-08-25 02:17:08,2009-03-14 14:41:42
22,c:100174,Company,100174,NaN,Paydirt,paydirt,/company/paydirt,software,operating,2011-01-25,NaN,paydirtapp.com,http://paydirtapp.com,paydirtapp,http://s3.amazonaws.com/crunchbase_prod_assets...,128.0,128.0,NaN,Online time tracking and invoicing,Paydirt produces online time tracking and invo...,"time-tracking, invoicing, freelancing",AUS,NaN,Abbotsford,Abbotsford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-01-01,2011-01-01,1.0,2.0,NaN,2011-09-07 02:12:18,2012-03-03 08:14:35
23,c:100178,Company,100178,NaN,Wreally,wreally,/company/wreally,web,operating,2009-03-01,NaN,wreally.com,http://wreally.com,wreallystudios,http://s3.amazonaws.com/crunchbase_prod_assets...,262.0,131.0,NaN,(W)real time web,Wreally is an independent web application deve...,"web-development, scribble, pixza, real-time-we...",NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,jasonbosco,2011-09-07 02:17:14,2011-09-24 13:13:32
24,c:10018,Company,10018,NaN,Demandbase,demandbase,/company/demandbase,analytics,operating,2006-01-01,NaN,demandbase.com,http://www.demandbase.com,Demandbase,http://s3.amazonaws.com/crunchbase_prod_assets...,249.0,49.0,NaN,NaN,Demandbase is the first targeting and personal...,NaN,USA,CA,San Francisco,SF Bay,NaN,NaN,NaN,NaN,2008-08-25,2013-03-28,3.0,33000000.0,2010-05-18,2013-03-01,3.0,19.0,jason,2008-08-25 03:35:42,2013-10-23 11:32:49
25,c:100180,Company,100180,NaN,AirSpeed,airspeed,/company/airspeed,software,operating,2011-01-01,NaN,airspeedapp.com,http://www.airspeedapp.com,airspeedapp,http://s3.amazonaws.com/crunchbase_prod_assets...,141.0,33.0,NaN,Sync Gmail and Salesforce,"AirSpeed makes it easy to copy Emails, Contact...","salesforce-com, google-apps, gmail, sync",USA,CA,San Francisco,SF Bay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-09-07 02:18:41,2012-12-13 04:36:39
26,c:100189,Company,100189,NaN,Locatrix Communications,locatrix communications,/company/locatrix-communications,mobile,operating,2003-11-01,NaN,locatrix.com,http://locatrix.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,2200.0,400.0,NaN,Mobile software developer,Locatrix Communications is one of Australia,"mobile, location-based, wireless, applications...",AUS,NaN,Brisbane,SF Bay,NaN,NaN,NaN,NaN,2003-11-01,2003-11-01,1.0,250000.0,2007-11-01,2007-11-01,1.0,2.0,mwhite41,2011-09-07 02:27:33,2013-10-11 09:51:41
27,c:10020,Company,10020,NaN,Threebrix E-services Pvt Ltd,threebrix e services pvt,/company/threebrix-e-services-pvt-ltd,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-08-25 04:03:25,2008-08-25 16:26:39
28,c:10021,Company,10021,NaN,Diditz,diditz,/company/diditz,network_hosting,operating,2008-01-01,NaN,diditz.com,http://www.diditz.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,134.0,58.0,NaN,NaN,Diditz is a social media website where you can...,"social-network, social-media, aggregation, gro...",IND,NaN,New Delhi,New Delhi,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN,2008-08-25 04:03:26,2013-11-15 20:27:51
29,c:100211,Company,100211,NaN,The Lions Group,the lions group,/company/the-lions-group,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-09-07 02:43:13,2011-09-24 13:14:04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462621,r:9958,Product,9958,c:14115,Dezidr,dezidr,/product/dezidr,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 09:43:37,2008-11-28 22:44:39
462622,r:9959,Product,9959,c:4630,Knowledge Plaza,knowledge plaza,/product/knowledge-plaza,NaN,live,2008-10-01,NaN,knowledgeplaza.net,http://www.knowledgeplaza.net,knowledgeplaza,http://s3.amazonaws.com/crunchbase_prod_assets...,840.0,253.0,NaN,NaN,KnowledgePlaza is a web platform that supports...,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010-05-17,2010-05-17,1.0,NaN,NaN,2008-11-28 09:43:41,2011-10-24 02:32:34
462623,r:9965,Product,9965,c:14119,Roxen Editorial Portal,roxen editorial portal,/product/roxen-editorial-portal,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 10:23:11,2008-11-28 22:51:20
462624,r:9966,Product,9966,c:14119,Roxen CMS,roxen cms,/product/roxen-cms,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 10:23:11,2008-11-28 22:51:20
462625,r:9967,Product,9967,c:14121,DreamFace 2.0,dreamface 2 0,/product/dreamface,NaN,live,2007-03-15,NaN,dreamface.org,http://www.dreamface.org,dreamface_org,NaN,NaN,NaN,NaN,NaN,NaN,"web-2-0, mashup, mashups, interactive, persona...",NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 10:23:49,2009-10-19 16:59:02
462626,r:9968,Product,9968,c:14122,Blaisic,blaisic,/product/blaisic,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 10:24:20,2008-11-28 22:51:55
462627,r:9969,Product,9969,c:14123,FirebirdCMS,firebirdcms,/product/firebirdcms,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 10:24:57,2008-11-28 22:52:14
462628,r:997,Product,997,c:1164,Nutrition Advisors Network,nutrition advisors network,/product/nutrition-advisors-network,NaN,operating,2008-01-01,NaN,nutrition.bitwine.com,http://nutrition.bitwine.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,940.0,650.0,NaN,NaN,"The Nutrition Advisors' Networkâ„¢, is powered...",NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-02-05 22:33:15,2008-08-23 19:26:01
462629,r:9971,Product,9971,c:14132,Vamooz,vamooz,/product/vamooz,NaN,beta,2008-11-27,NaN,vamooz.com,http://www.vamooz.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,362.0,80.0,NaN,NaN,Get the latest news from around the world and...,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 11:02:50,2008-12-06 14:52:55
462630,r:9972,Product,9972,c:14134,Publicity Generating Service,publicity generating service,/product/publicity-generating-service,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 11:07:01,2008-11-28 23:01:13
462631,r:9973,Product,9973,c:14140,Homethinking - Realtor Search,homethinking realtor search,/product/realtor-search,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 11:24:23,2008-11-28 23:03:58
462632,r:9974,Product,9974,c:14140,Homethinking - Neighborhoods,homethinking neighborhoods,/product/neighborhoods,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-10-29,2013-10-29,1.0,NaN,NaN,2008-11-28 11:24:23,2008-11-28 23:03:42
462633,r:9975,Product,9975,c:14140,Homethinking - Mortgage,homethinking mortgage,/product/mortgage,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 11:24:23,2008-11-28 23:03:21
462634,r:9976,Product,9976,c:14141,Pintarget.com,pintarget,/product/pintarget-com,NaN,live,2009-08-01,NaN,pintarget.com,http://www.pintarget.com,Pintarget,http://s3.amazonaws.com/crunchbase_prod_assets...,800.0,722.0,NaN,NaN,Pintarget helps people to research online. \r...,"research, concierge, search, recommendations, ...",NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-08-01,2009-08-01,1.0,NaN,NaN,2008-11-28 11:35:20,2009-11-30 20:11:04
462635,r:9977,Product,9977,c:14144,Momail mobile email,momail mobile email,/product/momail-mobile-email,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 12:00:47,2008-11-28 23:06:10
462636,r:9978,Product,9978,c:14145,LumoFlow,lumoflow,/product/lumo-flow,NaN,live,2008-01-01,NaN,lumoflow.com,http://www.lumoflow.com,lumoresearch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 12:03:27,2010-03-01 19:03:14
462637,r:998,Product,998,c:1164,Tech Advisors Network,tech advisors network,/product/tech-advisors-network,NaN,operating,2007-12-30,NaN,tech.bitwine.com,http://tech.bitwine.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,935.0,668.0,NaN,NaN,"The Nutrition Advisors' Networkâ„¢, is powered...",NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-02-05 22:33:15,2008-02-25 00:23:17
462638,r:9982,Product,9982,c:14151,Timesheet Management Software,timesheet management software,/product/timesheet-management-software,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 12:53:11,2008-11-28 23:10:44
462639,r:9987,Product,9987,c:12842,Sports Blog Network,sports blog network,/product/sports-blog-network,NaN,operating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-11-28 13:41:11,2008-11-28 23:12:26

In [11]:
df_offices= pd.read_csv('cb_offices.csv')
df_offices.head(3)

,id,object_id,office_id,description,region,address1,address2,city,zip_code,state_code,country_code,latitude,longitude,created_at,updated_at
0,1,c:1,1,NaN,Seattle,710 - 2nd Avenue,Suite 1100,Seattle,98104,WA,USA,47.603122,-122.333253,NaN,NaN
1,2,c:3,3,Headquarters,SF Bay,4900 Hopyard Rd,Suite 310,Pleasanton,94588,CA,USA,37.692934,-121.904945,NaN,NaN
2,3,c:4,4,NaN,SF Bay,135 Mississippi St,NaN,San Francisco,94107,CA,USA,37.764726,-122.394523,NaN,NaN

In [12]:
df_people= pd.read_csv('cb_people.csv') 
df_people.head(3)

   id object_id first_name last_name birthplace affiliation_name
0   1       p:2        Ben   Elowitz        NaN        Blue Nile
1   2       p:3      Kevin  Flaherty        NaN         Wetpaint
2   3       p:4       Raju   Vegesna        NaN             Zoho

In [13]:
df_relationships= pd.read_csv('cb_relationships.csv')
df_relationships

,id,relationship_id,person_object_id,relationship_object_id,start_at,end_at,is_past,sequence,title,created_at,updated_at
0,1,1,p:2,c:1,NaN,NaN,0,8,Co-Founder/CEO/Board of Directors,2007-05-25 07:03:54,2013-06-03 09:58:46
1,2,2,p:3,c:1,NaN,NaN,1,279242,VP Marketing,2007-05-25 07:04:16,2010-05-21 16:31:34
2,3,3,p:4,c:3,NaN,NaN,0,4,Evangelist,2007-05-25 19:33:03,2013-06-29 13:36:58
3,4,4,p:5,c:3,2006-03-01,2009-12-01,1,4,Senior Director Strategic Alliances,2007-05-25 19:34:53,2013-06-29 10:25:34
4,6,6,p:7,c:4,2005-07-01,2010-04-05,1,1,Chief Executive Officer,2007-05-25 20:05:33,2010-04-05 18:41:41
5,7,7,p:8,c:4,NaN,NaN,1,1,Senior Software Engineer,2007-05-25 20:06:45,2010-01-12 01:13:29
6,8,8,p:9,c:4,NaN,NaN,1,1,Systems Engineering Manager,2007-05-25 20:07:50,2010-08-03 22:00:58
7,9,9,p:10,c:5,NaN,NaN,0,1,"Founder and CEO, Board Of Directors",2007-05-25 21:51:46,2010-01-25 21:49:44
8,10,10,p:11,c:5,NaN,NaN,1,1,Co-Founder,2007-05-25 22:15:05,2011-08-11 23:48:45
9,11,11,p:12,c:5,NaN,NaN,1,3,"Chief Revenue Officer, VP of Operations",2007-05-25 22:15:59,2010-01-25 21:49:45
10,12,12,p:13,c:5,NaN,NaN,1,1,VP of Product Management,2007-05-25 22:16:59,2010-01-25 21:49:45
11,13,13,p:14,c:5,1993-07-04,1982-02-28,1,1,Co-founder,2007-05-25 22:17:27,2010-09-01 18:15:45
12,14,14,p:16,c:7299,NaN,NaN,1,2,Founder and CEO,2007-05-26 12:44:52,2011-07-19 00:05:01
13,15,15,p:17,c:7299,NaN,NaN,1,2,Co-founder and CTO,2007-05-26 12:45:46,2011-07-19 00:05:01
14,16,16,p:18,c:7299,2005-09-01,2009-10-01,1,1,"SVP, Technology and Partnerships",2007-05-26 12:47:13,2011-07-19 00:05:01
15,17,17,p:19,c:7299,2006-08-01,2009-08-01,1,8,"VP, Finance & Administration",2007-05-26 12:47:49,2011-10-28 03:08:15
16,18,18,p:20,c:7299,NaN,NaN,0,1,"VP, Sales",2007-05-26 12:48:20,2011-07-19 00:05:01
17,19,19,p:21,c:7299,NaN,NaN,0,1,"VP, Customer Service",2007-05-26 12:49:23,2011-07-19 00:05:01
18,20,20,p:22,c:7299,2005-10-01,2008-03-01,1,1,"VP, Business Development",2007-05-26 12:49:45,2013-08-07 08:51:20
19,21,21,p:23,c:7299,NaN,NaN,1,1,"VP, Engineering",2007-05-26 12:50:11,2011-07-19 00:05:02
20,22,22,p:24,c:7299,2007-01-01,2009-07-01,1,8,"VP, Marketing",2007-05-26 12:51:13,2013-11-12 23:51:51
21,23,23,p:25,c:7299,NaN,NaN,0,1,"VP, Product",2007-05-26 12:51:42,2011-07-19 00:05:02
22,25,25,p:29,f:3,1996-05-01,NaN,0,10,General Partner,2007-05-30 18:23:49,2013-08-12 04:05:45
23,27,27,p:30,c:9,2006-06-01,2009-07-01,1,279251,Founder & Chairman,2007-05-31 19:56:06,2013-06-27 04:29:57
24,28,28,p:31,c:9,NaN,NaN,0,3,Board Member,2007-05-31 19:57:11,2010-01-10 22:15:00
25,29,29,p:26,f:6,NaN,NaN,0,6,Partner,2007-05-31 20:15:01,2012-03-13 23:08:47
26,30,30,p:32,f:6,NaN,NaN,0,5,Partner,2007-05-31 20:15:31,2012-03-13 23:08:47
27,31,31,p:33,f:6,NaN,NaN,0,5,Partner,2007-05-31 20:16:11,2012-03-13 23:08:47
28,32,32,p:34,f:6,NaN,NaN,0,5,Executive General Partner,2007-05-31 20:16:40,2012-03-13 23:08:47
29,33,33,p:35,f:7,NaN,NaN,0,7,General Partner,2007-05-31 20:32:21,2013-08-26 20:19:07
...,...,...,...,...,...,...,...,...,...,...,...
402848,480878,480878,p:268523,c:25744,2007-01-01,2009-03-01,1,7,Vice President of Sales - NextWave Wireless,2013-12-12 14:13:51,2013-12-12 14:13:51
402849,480879,480879,p:268523,c:230516,2005-01-01,2007-01-01,1,6,Director of Business Development - Marvell Sem...,2013-12-12 14:14:24,2013-12-12 14:14:24
402850,480880,480880,p:268523,c:4304,2005-01-01,2005-01-01,1,5,Director of UMTS Business Development,2013-12-12 14:14:57,2013-12-12 14:14:57
402851,480881,480881,p:268523,c:4304,2004-01-01,2005-01-01,1,4,Regional Manager UMTS Business Development,2013-12-12 14:15:23,2013-12-12 14:15:23
402852,480882,480882,p:268523,c:4304,2000-01-01,2004-01-01,1,3,OMAP Business Development Manager,2013-12-12 14:15:50,2013-12-12 14:15:50
402853,480883,480883,p:158143,c:12612,NaN,NaN,0,4,"President & CEO, Wolters Kluwer Health, Clinic...",2013-12-12 14:16:24,2013-12-12 14:16:24
402854,480884,480884,p:268523,c:4304,1997-01-01,2000-01-01,1,2,Sales Account Manager,2013-12-12 14:16:25,2013-12-12 14:16:25
402855,480885,480885,p:268523,c:4304,1996-01-01,1997-01-01,1,1,Technical Sales Associate,2013-12-12 14:16:53,2013-12-12 14:16:53
402856,480886,480886,p:158143,c:218119,1999-01-01,2006-01-01,1,2,COO,2013-12-12 14:18:34,2013-12-12 14:18:34
402857,480887,480887,p:158143,c:1916,NaN,1999-01-01,1,1,VP / GM positions - GE Information Services,2013-12-12 14:21:27,2013-12-12 14:21:54
402858,480888,480888,p:158143,c:1916,NaN,NaN,1,3,Sr. Product/Service Management positions - GE ...,2013-12-12 14:21:27,2013-12-12 14:21:27
402859,480889,480889,p:268524,c:286211,NaN,NaN,1,1,Managing Partner,2013-12-12 14:23:11,2013-12-12 14:23:11
402860,480890,480890,p:268524,c:286212,NaN,NaN,1,2,Managing Partner,2013-12-12 14:23:33,2013-12-12 14:23:33
402861,480891,480891,p:268524,c:4715,NaN,NaN,1,3,Engagement Manager,2013-12-12 14:23:52,2013-12-12 14:23:52
402862,480892,480892,p:268524,c:4715,NaN,NaN,1,4,Independent Management Consultant and An Engag...,2013-12-12 14:24:13,2013-12-12 14:24:13
402863,480893,480893,p:268524,c:286213,NaN,NaN,1,5,Chief Executive Officer,2013-12-12 14:24:28,2013-12-12 14:24:28
402864,480894,480894,p:268589,c:12612,2006-06-01,NaN,0,4,"VP, Finance & Clinical Solutions",2013-12-12 14:26:05,2013-12-12 14:33:20
402865,480895,480895,p:268590,c:286215,NaN,NaN,0,1,Co-Founder,2013-12-12 14:27:53,2013-12-12 14:27:53
402866,480896,480896,p:268592,c:256200,NaN,NaN,0,1,CEO,2013-12-12 14:29:16,2013-12-12 14:29:16
402867,480897,480897,p:268593,c:256200,NaN,NaN,0,1,COO,2013-12-12 14:29:16,2013-12-12 14:29:16
402868,480898,480898,p:268589,c:12612,NaN,NaN,1,2,Accounting Manager for Facts & Comparisons,2013-12-12 14:33:21,2013-12-12 14:33:21
402869,480899,480899,p:268589,c:12612,NaN,NaN,1,3,"Controller, Wolters Kluwer Health",2013-12-12 14:33:21,2013-12-12 14:33:21
402870,480900,480900,p:268589,c:12612,1997-01-01,NaN,1,1,"Director, Accounting - Professional & Educatio...",2013-12-12 14:33:21,2013-12-12 14:33:21
402871,480901,480901,p:268527,c:39172,2012-04-01,2013-10-01,1,273047,"Director, Business Development",2013-12-12 14:34:17,2013-12-12 14:34:17
402872,480902,480902,p:268527,c:286217,2010-09-01,2012-04-01,1,1,"Sr. Manager, IP Analytics",2013-12-12 14:34:55,2013-12-12 14:34:55
402873,480903,480903,p:268527,c:286218,2005-01-01,2010-01-01,1,1,Sr. Consultant/Patent Agent,2013-12-12 14:35:35,2013-12-12 14:35:35
402874,480906,480906,p:268597,c:12612,NaN,NaN,0,1,"VP, GM & Editor In Chief - Clinical Decison Su...",2013-12-12 14:37:56,2013-12-12 14:37:56
402875,480907,480907,p:268528,c:286152,NaN,NaN,1,273049,Vice President,2013-12-12 14:39:36,2013-12-12 14:39:36
402876,480908,480908,p:268528,c:286220,NaN,NaN,1,1,"General Counsel, Director of Patents and Licen...",2013-12-12 14:39:48,2013-12-12 14:39:48
402877,480909,480909,p:268528,c:286221,NaN,NaN,1,1,Design Engineer,2013-12-12 14:40:04,2013-12-12 14:40:04

In [14]:
df_relationships.rename({'person_object_id': 'object_id'}, axis='columns', inplace=True)

## Merge People & Degrees

In [15]:
#Created dataframe that merges the info
df_peep= pd.merge(df_people, df_degrees, on='object_id')
df_peep.head(5)

,id_x,object_id,first_name,last_name,birthplace,affiliation_name,id_y,degree_type,subject,institution,graduated_at,created_at,updated_at
0,1,p:2,Ben,Elowitz,NaN,Blue Nile,699,BS,Electrical Engineering/Computer Science,"University of California, Berkeley",1994-01-01,2008-05-06 00:05:48,2008-05-06 00:05:48
1,1,p:2,Ben,Elowitz,NaN,Blue Nile,700,BS,Applied Mathematics,"University of California, Berkeley",1994-01-01,2008-05-06 00:06:10,2008-05-06 00:06:10
2,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38
3,2,p:3,Kevin,Flaherty,NaN,Wetpaint,707,MBA,NaN,Indiana University,NaN,2008-05-07 19:41:24,2013-11-21 09:43:38
4,4,p:5,Ian,Wenig,NaN,Zoho,47870,Degree,Advanced Business Professional Course,The Aji Network,2005-01-01,2013-06-29 13:33:08,2013-06-29 13:33:08

In [16]:
#Check data types 
df_peep.dtypes

id_x                 int64
object_id           object
first_name          object
last_name           object
birthplace          object
affiliation_name    object
id_y                 int64
degree_type         object
subject             object
institution         object
graduated_at        object
created_at          object
updated_at          object
dtype: object

In [17]:
#drop birthplace useless columns
#df_peep.drop(['birthplace','graduated_at'], axis=1, inplace= True)

#### Move the info per person and not for two rows

In [18]:
for unique_value in df_peep.object_id.unique():
    df_tmp = df_peep.loc[df_peep['object_id'] == unique_value]
    
    no_rows = df_tmp.shape[0]
    if no_rows > 1:
        print('merge rows into one')
    else:
        print('this row is unique')
    
    print(df_tmp)
    break

merge rows into one
   id_x object_id first_name last_name birthplace affiliation_name  id_y  \
0     1       p:2        Ben   Elowitz        NaN        Blue Nile   699
1     1       p:2        Ben   Elowitz        NaN        Blue Nile   700

  degree_type                                  subject  \
0          BS  Electrical Engineering/Computer Science
1          BS                      Applied Mathematics

                          institution graduated_at           created_at  \
0  University of California, Berkeley   1994-01-01  2008-05-06 00:05:48
1  University of California, Berkeley   1994-01-01  2008-05-06 00:06:10

            updated_at
0  2008-05-06 00:05:48
1  2008-05-06 00:06:10

In [19]:
# merge the name
df_peep['full_name'] = df_peep['first_name'] + ' ' +df_peep['last_name']

### How df_people looks now

In [20]:
df_peep

,id_x,object_id,first_name,last_name,birthplace,affiliation_name,id_y,degree_type,subject,institution,graduated_at,created_at,updated_at,full_name
0,1,p:2,Ben,Elowitz,NaN,Blue Nile,699,BS,Electrical Engineering/Computer Science,"University of California, Berkeley",1994-01-01,2008-05-06 00:05:48,2008-05-06 00:05:48,Ben Elowitz
1,1,p:2,Ben,Elowitz,NaN,Blue Nile,700,BS,Applied Mathematics,"University of California, Berkeley",1994-01-01,2008-05-06 00:06:10,2008-05-06 00:06:10,Ben Elowitz
2,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38,Kevin Flaherty
3,2,p:3,Kevin,Flaherty,NaN,Wetpaint,707,MBA,NaN,Indiana University,NaN,2008-05-07 19:41:24,2013-11-21 09:43:38,Kevin Flaherty
4,4,p:5,Ian,Wenig,NaN,Zoho,47870,Degree,Advanced Business Professional Course,The Aji Network,2005-01-01,2013-06-29 13:33:08,2013-06-29 13:33:08,Ian Wenig
5,4,p:5,Ian,Wenig,NaN,Zoho,47871,BS,"Biology, Psychology",McGill University,1986-01-01,2013-06-29 13:33:27,2013-06-29 13:33:27,Ian Wenig
6,5,p:6,Kevin,Rose,"Redding, CA",i/o Ventures,15624,NaN,NaN,"University of Nevada, Las Vegas",NaN,2011-08-17 22:18:35,2011-08-17 22:18:35,Kevin Rose
7,5,p:6,Kevin,Rose,"Redding, CA",i/o Ventures,69509,NaN,NaN,Montessori,1983-01-01,2013-08-26 09:39:41,2013-08-26 09:39:41,Kevin Rose
8,6,p:7,Jay,Adelson,"Detroit, MI",Digg,22649,NaN,"Film and Broadcasting, Computer Science Concen...",Boston University,1992-01-01,2012-09-15 22:58:01,2012-09-15 22:58:01,Jay Adelson
9,7,p:8,Owen,Byrne,NaN,Digg,1027,BS,Computer Science,Saint Mary's (Canada),1986-01-01,2008-06-17 22:52:19,2008-06-18 06:54:21,Owen Byrne
10,7,p:8,Owen,Byrne,NaN,Digg,1028,MBA,Business,Dalhousie (Canada),1994-01-01,2008-06-17 22:52:54,2008-06-18 06:54:38,Owen Byrne
11,8,p:9,Ron,Gorodetzky,NaN,Digg,8161,NaN,Computer Engineering,"University of California, San Diego (UCSD)",2003-01-01,2010-07-31 06:06:20,2010-08-02 17:29:48,Ron Gorodetzky
12,9,p:10,Mark,Zuckerberg,NaN,Facebook,2415,NaN,Computer Science,Harvard University,NaN,2009-03-24 22:50:22,2013-03-28 22:26:47,Mark Zuckerberg
13,10,p:11,Dustin,Moskovitz,"Gainesville, FL",Facebook,13476,No degree,NaN,Harvard University,NaN,2011-05-26 15:48:52,2012-05-29 11:07:00,Dustin Moskovitz
14,11,p:12,Owen,Van Natta,NaN,Asana,1652,BS,NaN,"University of California, Santa Cruz",NaN,2008-09-12 18:30:08,2010-08-13 17:22:47,Owen Van Natta
15,12,p:13,Matt,Cohler,NaN,LinkedIn,1049,BA,"Music Theory, Computer Science, and Finance",Yale University,NaN,2008-06-19 18:13:06,2008-06-19 18:13:06,Matt Cohler
16,14,p:16,Alex,Welch,NaN,C7 Group,3955,BA,Computer Information Systems,Colorado State University,NaN,2009-08-03 19:47:45,2009-08-03 19:47:45,Alex Welch
17,15,p:17,Darren,Crystal,NaN,Photobucket,3956,NaN,Electrical Engineering,University of Texas at Austin,NaN,2009-08-03 19:50:12,2009-08-03 19:50:23,Darren Crystal
18,16,p:18,Michael,Clark,NaN,Photobucket (Old),4939,BS,Human Communications and Public Affairs,University of Denver,1996-01-01,2009-11-24 22:25:58,2011-02-08 22:51:15,Michael Clark
19,17,p:19,Greg,Wimmer,NaN,Photobucket,56433,BS,Finance & Accounting,University of Oregon,1983-01-01,2013-07-27 04:36:03,2013-07-27 04:36:03,Greg Wimmer
20,20,p:22,Peter,Pham,NaN,"Photobucket, Inc.",4840,BS,Biology and Business Management,UC Irvine,2008-01-01,2009-11-16 22:34:41,2013-08-07 08:43:55,Peter Pham
21,22,p:24,Alice,Lankester,"Surrey, England",Apple,46696,BA,"History, Decorative Arts",University of Leeds,1982-01-01,2013-06-25 15:13:35,2013-06-25 15:13:35,Alice Lankester
22,24,p:26,Peter,Thiel,NaN,Confinity,1142,BA,Philosophy,Stanford University,NaN,2008-06-30 06:37:15,2008-06-30 06:37:15,Peter Thiel
23,24,p:26,Peter,Thiel,NaN,Confinity,1143,JD,Law,"Stanford University, Law School",NaN,2008-06-30 06:37:33,2010-04-03 22:30:11,Peter Thiel
24,25,p:29,Gus,Tai,NaN,BillShrink,41576,BA,Applied Mathematics,Harvard University,NaN,2013-06-04 09:35:59,2013-06-04 09:35:59,Gus Tai
25,25,p:29,Gus,Tai,NaN,BillShrink,41577,MS,Materials Science,"Massachusetts Institute of Technology (MIT), S...",NaN,2013-06-04 09:35:59,2013-06-04 09:35:59,Gus Tai
26,25,p:29,Gus,Tai,NaN,BillShrink,60965,MBA,NaN,M.I.T. Sloan School of Management,NaN,2013-08-07 04:58:54,2013-08-07 04:58:54,Gus Tai
27,26,p:30,David,Sacks,NaN,GumGum,5254,JD,Law,"University of Chicago, School of Law",1998-01-01,2009-12-22 18:59:17,2009-12-22 20:49:50,David Sacks
28,26,p:30,David,Sacks,NaN,GumGum,5255,BA,Economics,Stanford University,1994-01-01,2009-12-22 19:00:19,2009-12-22 20:49:52,David Sacks
29,27,p:31,Alan,Braverman,NaN,Geni,7083,BS,Computer Science,University of Illinois,1995-01-01,2010-05-13 01:07:44,2010-05-13 07:48:28,Alan Braverman
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109026,226633,p:268504,Carlos,Tapiador,NaN,"InvierteMe,SL",109566,NaN,Information Technology,Universidad Pontificia de Salamanca,NaN,2013-12-12 11:27:34,2013-12-12 11:27:34,Carlos Tapiador
109027,226638,p:268510,Robert,"L. ""Chip"" Harris",NaN,Unaffiliated,109576,NaN,NaN,University of Southern California,1980-01-01,2013-12-12 11:57:10,2013-12-12 11:57:22,"Robert L. ""Chip"" Harris"
109028,226639,p:268511,Matthew,Vella,NaN,Unaffiliated,109579,B.S.,NaN,Electrical Engineering Carleton University,NaN,2013-12-12 12:02:21,2013-12-12 12:02:21,Matthew Vella
109029,226639,p:268511,Matthew,Vella,NaN,Unaffiliated,109580,J.D.,NaN,University of Toronto Law School,NaN,2013-12-12 12:02:38,2013-12-12 12:02:38,Matthew Vella
109030,226641,p:268513,Marvin,Key,NaN,Unaffiliated,109581,BS,Financial Management,Clemson University,1982-01-01,2013-12-12 12:06:31,2013-12-12 12:06:31,Marvin Key
109031,226641,p:268513,Marvin,Key,NaN,Unaffiliated,109582,MBA,"Finance, General",Southern Methodist University - Cox School of ...,1983-01-01,2013-12-12 12:07:14,2013-12-12 12:07:14,Marvin Key
109032,226642,p:268514,Robert,Stewart,NaN,Unaffiliated,109583,bachelors,economics,University of Colorado/Boulder,NaN,2013-12-12 12:14:26,2013-12-12 12:14:26,Robert Stewart
109033,226644,p:268516,Jonathan,Taub,NaN,Unaffiliated,109584,BS,finance,"Wharton School of Business , University of Pen...",NaN,2013-12-12 12:20:49,2013-12-12 12:20:49,Jonathan Taub
109034,226644,p:268516,Jonathan,Taub,NaN,Unaffiliated,109585,JD,NaN,Harvard Law School,NaN,2013-12-12 12:21:08,2013-12-12 12:21:08,Jonathan Taub
109035,226645,p:268517,Robert,Rauker,NaN,Unaffiliated,109589,B.S.,Engineering,University of Massachusetts,NaN,2013-12-12 12:28:03,2013-12-12 12:28:03,Robert Rauker
109036,226645,p:268517,Robert,Rauker,NaN,Unaffiliated,109590,M.B.A.,NaN,University of Massachusetts,NaN,2013-12-12 12:28:23,2013-12-12 12:28:23,Robert Rauker
109037,226645,p:268517,Robert,Rauker,NaN,Unaffiliated,109591,J.D.,NaN,University of New Hampshire School of Law,NaN,2013-12-12 12:28:42,2013-12-12 12:28:42,Robert Rauker
109038,226646,p:268519,Charlotte,Rutherford,NaN,Unaffiliated,109592,Bachelor of Science,Engineering,"Auburn University, Auburn, Alabama",1977-01-01,2013-12-12 12:43:14,2013-12-12 12:43:14,Charlotte Rutherford
109039,226646,p:268519,Charlotte,Rutherford,NaN,Unaffiliated,109593,Master of Science,Engineering,"Auburn University, Auburn, Alabama",1978-01-01,2013-12-12 12:43:47,2013-12-12 12:43:47,Charlotte Rutherford
109040,226646,p:268519,Charlotte,Rutherford,NaN,Unaffiliated,109594,Juris Doctor,NaN,"Loyola University, New Orleans, Louisiana",1985-01-01,2013-12-12 12:44:53,2013-12-12 12:44:53,Charlotte Rutherford
109041,226646,p:268519,Charlotte,Rutherford,NaN,Unaffiliated,109595,MBA,"Finance, General","Rutgers University, Newark, New Jersey",1998-01-01,2013-12-12 12:45:45,2013-12-12 12:45:45,Charlotte Rutherford
109042,226647,p:268520,Hironori,Seki,NaN,Unaffiliated,109596,B.S.,physics,Waseda University,NaN,2013-12-12 13:56:08,2013-12-12 13:56:08,Hironori Seki
109043,226647,p:268520,Hironori,Seki,NaN,Unaffiliated,109597,M.S.,Physics,Waseda University,NaN,2013-12-12 13:56:37,2013-12-12 13:56:37,Hironori Seki
109044,226648,p:268521,Erik,Ahroon,NaN,Unaffiliated,109598,BS,Mechanical Engineering,"University of California, Santa Barbara",2002-01-01,2013-12-12 14:01:29,2013-12-12 14:01:29,Erik Ahroon
109045,226648,p:268521,Erik,Ahroon,NaN,Unaffiliated,109599,MBA,NaN,"University of California, Irvine - The Paul Me...",2006-01-01,2013-12-12 14:02:21,2013-12-12 14:02:21,Erik Ahroon
109046,226651,p:268524,James,Trueman,NaN,Unaffiliated,109602,Masters,Business Administration,Wharton School,NaN,2013-12-12 14:21:11,2013-12-12 14:21:11,James Trueman
109047,226651,p:268524,James,Trueman,NaN,Unaffiliated,109603,B.S.,NaN,University of California at Berkeley,NaN,2013-12-12 14:21:38,2013-12-12 14:21:38,James Trueman
109048,226651,p:268524,James,Trueman,NaN,Unaffiliated,109604,Masters,Business Administration,"Wharton School of Business , University of Pen...",NaN,2013-12-12 14:22:33,2013-12-12 14:22:33,James Trueman
109049,226654,p:268527,Harry,Wei,NaN,Unaffiliated,109607,MS & BS,Engineering,South China University of Technology,NaN,2013-12-12 14:31:21,2013-12-12 14:31:21,Harry Wei
109050,226654,p:268527,Harry,Wei,NaN,Unaffiliated,109608,PhD,Engineering,Clarkson University,NaN,2013-12-12 14:31:48,2013-12-12 14:31:48,Harry Wei
109051,226655,p:268528,Edward,J. Treska,NaN,Unaffiliated,109609,B.S.,Electrical Engineering,Colorado State University,NaN,2013-12-12 14:38:15,2013-12-12 14:38:15,Edward J. Treska
109052,226655,p:268528,Edward,J. Treska,NaN,Unaffiliated,109610,J.D.,NaN,University of San Diego School of Law,NaN,2013-12-12 14:38:33,2013-12-12 14:38:33,Edward J. Treska
109053,226687,p:268560,Drew,Langloh,NaN,Unaffiliated,109575,MBA,NaN,Samford University,2008-01-01,2013-12-12 11:52:31,2013-12-12 11:52:31,Drew Langloh
109054,226705,p:268589,John,Pins,NaN,Unaffiliated,109605,B.S.,Accounting,Iowa State University,NaN,2013-12-12 14:28:58,2013-12-12 14:28:58,John Pins
109055,226705,p:268589,John,Pins,NaN,Unaffiliated,109606,CPA,NaN,American Institute of Certtified Public Accoun...,NaN,2013-12-12 14:28:58,2013-12-12 14:28:58,John Pins

## Merge Object, Offices, Milestones, Ipos

In [21]:
df_offices.head(3)

,id,object_id,office_id,description,region,address1,address2,city,zip_code,state_code,country_code,latitude,longitude,created_at,updated_at
0,1,c:1,1,NaN,Seattle,710 - 2nd Avenue,Suite 1100,Seattle,98104,WA,USA,47.603122,-122.333253,NaN,NaN
1,2,c:3,3,Headquarters,SF Bay,4900 Hopyard Rd,Suite 310,Pleasanton,94588,CA,USA,37.692934,-121.904945,NaN,NaN
2,3,c:4,4,NaN,SF Bay,135 Mississippi St,NaN,San Francisco,94107,CA,USA,37.764726,-122.394523,NaN,NaN

In [22]:
pd.options.display.max_columns = None

In [23]:
df_objects.head(3)

,id,entity_type,entity_id,parent_id,name,normalized_name,permalink,category_code,status,founded_at,closed_at,domain,homepage_url,twitter_username,logo_url,logo_width,logo_height,short_description,description,overview,tag_list,country_code,state_code,city,region,first_investment_at,last_investment_at,investment_rounds,invested_companies,first_funding_at,last_funding_at,funding_rounds,funding_total_usd,first_milestone_at,last_milestone_at,milestones,relationships,created_by,created_at,updated_at
0,c:1,Company,1,NaN,Wetpaint,wetpaint,/company/wetpaint,web,operating,2005-10-17,NaN,wetpaint-inc.com,http://wetpaint-inc.com,BachelrWetpaint,http://s3.amazonaws.com/crunchbase_prod_assets...,401.0,54.0,NaN,Technology Platform Company,Wetpaint is a technology platform company that...,"wiki, seattle, elowitz, media-industry, media-...",USA,WA,Seattle,Seattle,NaN,NaN,NaN,NaN,2005-10-01,2008-05-19,3.0,39750000.0,2010-09-05,2013-09-18,5.0,17.0,initial-importer,2007-05-25 06:51:27,2013-04-13 03:29:00
1,c:10,Company,10,NaN,Flektor,flektor,/company/flektor,games_video,acquired,NaN,NaN,flektor.com,http://www.flektor.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,186.0,85.0,NaN,NaN,Flektor is a rich-media mash-up platform that ...,"flektor, photo, video",USA,CA,Culver City,Los Angeles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,initial-importer,2007-05-31 21:11:51,2008-05-23 23:23:14
2,c:100,Company,100,NaN,There,there,/company/there,games_video,acquired,NaN,NaN,there.com,http://www.there.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,107.0,34.0,NaN,NaN,There.com is an online virtual world where any...,"virtualworld, there, teens",USA,CA,San Mateo,SF Bay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-02-01,2011-09-23,4.0,12.0,initial-importer,2007-08-06 23:52:45,2013-11-04 02:09:48

In [24]:
df_objects.rename(columns={"id": "object_id"}, inplace= True)

In [25]:
#Created dataframe that merges the info
df_companies= pd.merge(df_objects, df_offices, on= 'object_id')
df_merger= pd.merge(df_milestones, df_ipos, on= 'object_id')
df_companies = pd.merge(df_companies, df_merger, on= 'object_id')

In [26]:
df_companies.shape

(5211, 74)

In [27]:
df_companies.columns

Index(['object_id', 'entity_type', 'entity_id', 'parent_id', 'name',
       'normalized_name', 'permalink', 'category_code', 'status', 'founded_at',
       'closed_at', 'domain', 'homepage_url', 'twitter_username', 'logo_url',
       'logo_width', 'logo_height', 'short_description', 'description_x',
       'overview', 'tag_list', 'country_code_x', 'state_code_x', 'city_x',
       'region_x', 'first_investment_at', 'last_investment_at',
       'investment_rounds', 'invested_companies', 'first_funding_at',
       'last_funding_at', 'funding_rounds', 'funding_total_usd',
       'first_milestone_at', 'last_milestone_at', 'milestones',
       'relationships', 'created_by', 'created_at_x_x', 'updated_at_x_x', 'id',
       'office_id', 'description_y', 'region_y', 'address1', 'address2',
       'city_y', 'zip_code', 'state_code_y', 'country_code_y', 'latitude',
       'longitude', 'created_at_y_x', 'updated_at_y_x', 'id_x', 'milestone_at',
       'milestone_code', 'description', 'source_url_x', 'source_description_x',
       'created_at_x_y', 'updated_at_x_y', 'id_y', 'ipo_id',
       'valuation_amount', 'valuation_currency_code', 'raised_amount',
       'raised_currency_code', 'public_at', 'stock_symbol', 'source_url_y',
       'source_description_y', 'created_at_y_y', 'updated_at_y_y'],
      dtype='object')

In [28]:
df_companies.head(70)

,object_id,entity_type,entity_id,parent_id,name,normalized_name,permalink,category_code,status,founded_at,closed_at,domain,homepage_url,twitter_username,logo_url,logo_width,logo_height,short_description,description_x,overview,tag_list,country_code_x,state_code_x,city_x,region_x,first_investment_at,last_investment_at,investment_rounds,invested_companies,first_funding_at,last_funding_at,funding_rounds,funding_total_usd,first_milestone_at,last_milestone_at,milestones,relationships,created_by,created_at_x_x,updated_at_x_x,id,office_id,description_y,region_y,address1,address2,city_y,zip_code,state_code_y,country_code_y,latitude,longitude,created_at_y_x,updated_at_y_x,id_x,milestone_at,milestone_code,description,source_url_x,source_description_x,created_at_x_y,updated_at_x_y,id_y,ipo_id,valuation_amount,valuation_currency_code,raised_amount,raised_currency_code,public_at,stock_symbol,source_url_y,source_description_y,created_at_y_y,updated_at_y_y
0,c:100844,Company,100844,NaN,Attunity,attunity,/company/attunity,software,ipo,NaN,NaN,attunity.com,http://www.attunity.com,attunity,http://s3.amazonaws.com/crunchbase_prod_assets...,1635.0,379.0,Attunity provides information-availability sof...,NaN,Attunity is a leading provider of information ...,NaN,USA,MA,Burlington,Boston,NaN,NaN,NaN,NaN,2004-06-01,2011-09-21,4.0,1.050000e+07,2012-02-14,2012-02-14,1.0,1.0,timircha,2011-09-07 13:47:49,2013-07-16 15:49:48,52712,60335,NaN,Boston,70 Blanchard Road,NaN,Burlington,01803,MA,USA,NaN,NaN,NaN,NaN,18406,2012-02-14,other,Attunity gets $1M license from mystery cable c...,http://www.masshightech.com/stories/2012/02/13...,Attunity gets $1M license from mystery cable c...,2012-02-15 02:39:55,2012-02-15 02:39:55,941,1022,NaN,USD,NaN,USD,2007-08-01,ATTU,http://www.attunity.com/news/attunity-receives...,ATTUNITY receives Nasdaq,2013-07-16 16:05:56,2013-07-16 17:51:40
1,c:10106,Company,10106,NaN,Thomson Reuters,thomson reuters,/company/thomson-reuters,public_relations,ipo,2008-04-17,NaN,thomsonreuters.com,http://thomsonreuters.com,ThomsonReuters,http://s3.amazonaws.com/crunchbase_prod_assets...,680.0,680.0,NaN,Intelligent Information Provider,Thomson Reuters is the world's leading source ...,NaN,USA,NY,New York,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010-06-08,2013-04-29,4.0,100.0,NaN,2008-08-26 07:43:06,2012-08-09 13:33:58,78740,91411,NaN,New York,3 Times Square,NaN,New York,10036,NY,USA,40.756432,-73.987185,NaN,NaN,5421,2010-06-08,other,Thomson Reuters has acquired UAE legislation L...,http://fusiondiginet.com/2010/06/08/thomson-re...,Thomson Reuters has acquired UAE legislation L...,2010-07-08 12:35:06,2010-07-08 12:35:06,1018,1110,NaN,USD,NaN,USD,2002-06-21,NYSE:TRI,NaN,NaN,2013-08-26 10:53:26,2013-08-26 20:14:31
2,c:10222,Company,10222,NaN,Hitachi,hitachi,/company/hitachi,public_relations,ipo,NaN,NaN,hitachi.com,http://www.hitachi.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,155.0,82.0,NaN,NaN,"Since its founding in 1910, Hitachi has respon...",NaN,JPN,NaN,Tokyo,Tokyo,2013-11-03,2013-11-03,1.0,1.0,NaN,NaN,NaN,NaN,2009-12-09,2013-08-23,3.0,44.0,NaN,2008-08-27 21:43:47,2013-11-25 08:36:12,61291,71209,NaN,Tokyo,"6-6, Marunouchi 1-chome",Chiyoda-ku,Tokyo,100-8280,NaN,JPN,NaN,NaN,NaN,NaN,2885,2009-12-09,other,Hitachi Acquires Software Assets Related to Ne...,http://www.hitachi.com/New/cnews/091209.html,Hitachi Acquires Software Assets Related to Ne...,2010-01-25 12:08:01,2010-01-25 12:09:07,741,804,NaN,USD,NaN,USD,1978-01-13,NYSE:HIT,NaN,NaN,2012-04-12 04:27:30,2012-04-12 04:27:30
3,c:104377,Company,104377,NaN,Tremor Video,tremor video,/company/tremor-video,advertising,ipo,2005-01-01,NaN,tremorvideo.com,http://tremorvideo.com,tremorvideo,http://s3.amazonaws.com/crunchbase_prod_assets...,201.0,75.0,NaN,NaN,Tremor Video is a digital video technology com...,NaN,USA,NY,New York,New York,NaN,NaN,NaN,NaN,2006-03-01,2011-09-12,8.0,1.164000e+08,2011-12-01,2013-05-23,3.0,24.0,timircha,2011-09-13 12:12:56,2013-03-20 01:58:12,52987,60659,NaN,New York,53 West 23rd Street,12th Floor,New York,10010,NY,USA,NaN,NaN,NaN,NaN,17734,2012-01-20,other,Tremor Video Acquires,http://techcrunch.com/2012/01/20/tremor-video-...,Tremor Video Acquires,2012-01-21 02:53:42,2012-01-21 02:53:42,850,923,NaN,USD,75000000.0,USD,2013-06-27,NYSE:TRMR,http://www.bizjournals.com/newyork/news/2013/0...,Tremor Video,2013-05-24 05:04:39,2013-07-18 18:03:13
4,c:104377,Company,104377,NaN,Tremor Video,tremor video,/company/tremor-video,advertising,ipo,2005-01-01,NaN,tremorvideo.com,http://tremorvideo.com,tremorvideo,http://s3.amazonaws.com/crunchbase_prod_assets...,201.0,75.0,NaN,NaN,Tremor Video is a digital video technology com...,NaN,USA,NY,New York,New York,NaN,NaN,NaN,NaN,2006-03-01,2011-09-12,8.0,1.164000e+08,2011-12-01,2013-05-23,3.0,24.0,timircha,2011-09-13 12:12:56,2013-03-20 01:58:12,58252,67339,NaN,Toronto,NaN,NaN,Toronto,NaN,NaN,CAN,NaN,NaN,NaN,NaN,17734,2012-01-20,other,Tremor Video Acquires,http://techcrunch.com/2012/01/20/tremor-video-...,Tremor Video Acquires,2012-01-21 02:53:42,2012-01-21 02:53:42,850,923,NaN,USD,75000000.0,USD,2013-06-27,NYSE:TRMR,http://www.bizjournals.com/newyork/news/2013/0...,Tremor Video,2013-05-24 05:04:39,2013-07-18 18:03:13
5,c:104377,Company,104377,NaN,Tremor Video,tremor video,/company/tremor-video,advertising,ipo,2005-01-01,NaN,tremorvideo.com,http://tremorvideo.com,tremorvideo,http://s3.amazonaws.com/crunchbase_prod_assets...,201.0,75.0,NaN,NaN,Tremor Video is a digital video technology com...,NaN,USA,NY,New York,New York,NaN,NaN,NaN,NaN,2006-03-01,2011-09-12,8.0,1.164000e+08,2011-12-01,2013-05-23,3.0,24.0,timircha,2011-09-13 12:12:56,2013-03-20 01:58:12,58253,67340,NaN,Detroit,NaN,NaN,Detroit,NaN,MI,USA,NaN,NaN,NaN,NaN,17734,2012-01-20,other,Tremor Video Acquires,http://techcrunch.com/2012/01/20/tremor-video-...,Tremor Video Acquires,2012-01-21 02:53:42,2012-01-21 02:53:42,850,923,NaN,USD,75000000.0,USD,2013-06-27,NYSE:TRMR,http://www.bizjournals.com/newyork/news/2013/0...,Tremor Video,2013-05-24 05:04:39,2013-07-18 18:03:13
6,c:104377,Company,104377,NaN,Tremor Video,tremor video,/company/tremor-video,advertising,ipo,2005-01-01,NaN,tremorvideo.com,http://tremorvideo.com,tremorvideo,http://s3.amazonaws.com/crunchbase_prod_assets...,201.0,75.0,NaN,NaN,Tremor Video is a digital video technology com...,NaN,USA,NY,New York,New York,NaN,NaN,NaN,NaN,2006-03-01,2011-09-12,8.0,1.164000e+08,2011-12-01,2013-05-23,3.0,24.0,timircha,2011-09-13 12:12:56,2013-03-20 01:58:12,58254,67341,NaN,Atlanta,NaN,NaN,Atlanta,NaN,GA,USA,NaN,NaN,NaN,NaN,17734,2012-01-20,other,Tremor Video Acquires,http://techcrunch.com/2012/01/20/tremor-video-...,Tremor Video Acquires,2012-01-21 02:53:42,2012-01-21 02:53:42,850,923,NaN,USD,75000000.0,USD,2013-06-27,NYSE:TRMR,http://www.bizjournals.com/newyork/news/2013/0...,Tremor Video,2013-05-24 05:04:39,2013-07-18 18:03:13
7,c:10453,Company,10453,NaN,Bankrate,bankrate,/company/bankrate,web,ipo,1993-01-01,NaN,bankrate.com,http://bankrate.com,Bankrate,http://s3.amazonaws.com/crunchbase_prod_assets...,201.0,52.0,NaN,Personal Finance Portal,"Bankrate is a leading publisher, aggregator an...",NaN,USA,FL,North Palm Beach,Palm Beach,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-07-22,2011-06-01,3.0,5.0,joel,2008-09-03 06:26:43,2013-04-03 10:51:19,32422,37121,Headquarters,Palm Beach,11760 U.S. 1,#500,North Palm Beach,33408,FL,USA,NaN,NaN,NaN,NaN,1601,2009-07-22,other,Bankrate acquired by Apax Partners,http://paidcontent.org/article/419-breaking-ba...,Bankrate Being Acquired By Apax For $571 Milli...,2009-07-22 22:11:14,2009-07-22 22:11:14,1028,1121,NaN,USD,NaN,USD,2011-06-24,NYSE:RATE,NaN,NaN,2013-08-27 07:18:08,2013-08-27 07:18:08
8,c:10475,Company,10475,NaN,Abbott Labs,abbott labs,/company/abbott,biotech,ipo,1991-01-01,NaN,abbott.com,http://www.abbott.com,abbottnews,http://s3.amazonaws.com/crunchbase_prod_assets...,149.0,69.0,NaN,Genomic Disease Management,"Abbott Molecular Inc., a genomic disease manag...",NaN,USA,IL,Des Plaines,Chicago,2007-01-30,2007-11-27,2.0,2.0,2011-03-15,2011-03-15,1.0,1.000000e+05,2009-01-01,2013-08-19,2.0,66.0,NaN,2008-09-03 21:51:05,2009-09-24 23:23:17,18586,21876,NaN,Chicago,1300 East Touhy,NaN,Des Plaines,60018-3315,IL,USA,NaN,NaN,NaN,NaN,19952,2012-05-03,other,Abbott Buys Action Pharma Hormone For $110M,http://pevc.dowjones.com/article?an=DJFVW00020...,Abbott Buys Action Pharma Hormone For $110M,2012-05-04 05:04:30,2012-05-04 05:04:30,310,351,NaN,USD,NaN,USD,1990-01-02,NYSE:ABT,NaN,NaN,2010-03-10 10:57:24,2013-10-28 03:07:54
9,c:10475,Company,10475,NaN,Abbott Labs,abbott labs,/company/abbott,biotech,ipo,1991-01-01,NaN,abbott.com,http://www.abbott.com,abbottnews,http://s3.amazonaws.com/crunchbase_prod_assets...,149.0,69.0,NaN,Genomic Disease Management,"Abbott Molecular Inc., a genomic disease manag...",NaN,USA,IL,Des Plaines,Chicago,2007-01-30,2007-11-27,2.0,2.0,2011-03-15,2011-03-15,1.0,1.000000e+05,2009-01-01,2013-08-19,2.0,66.0,NaN,2008-09-03 21:51:05,2009-09-24 23:23:17,18586,21876,NaN,Chicago,1300 East Touhy,NaN,Des Plaines,60018-3315,IL,USA,NaN,NaN,NaN,NaN,34043,2013-08-19,other,Abbott closes $250M deal for eye surgery biz,http://www.fiercemedicaldevices.com/story/abbo...,Abbott closes $250M deal for eye surgery biz,2013-08-20 04:39:47,2013-08-22 02:57:23,310,351,NaN,USD,NaN,USD,1990-01-02,NYSE:ABT,NaN,NaN,2010-03-10 10:57:24,2013-10-28 03:07:54
10,c:10545,Company,10545,NaN,LRAD Corporation,lrad,/company/american-technology-corp,semiconductor,ipo,1980-01-01,NaN,lradx.com,http://www.lradx.com,LRADX,http://s3.amazonaws.com/crunchbase_prod_assets...,300.0,82.0,NaN,sound technologies and acoustic products,"LRAD Corporation, formerly American Technology...",NaN,USA,CA,San Diego,San Diego,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-08-17,2011-08-17,1.0,2.0,NaN,2008-09-05 00:54:35,2013-07-04 21:40:04,20986,24611,HQ,San Diego,15378 Avenue of Science,Suite 100,San Diego,92128,CA,USA,NaN,NaN,NaN,NaN,7505,2010-10-06,other,LRAD Corporation to Report Record Revenues of ...,http://www.freshnews.com/news/393032/lrad-corp...,LRAD Corporation to Report Record Revenues of ...,2010-10-08 03:42:32,2010-10-08 03:42:32,440,489,NaN,USD,NaN,NaN,NaN,NASDAQ:LRAD,NaN,NaN,2010-10-08 03:40:14,2010-10-08 03:40:14
11,c:10545,Company,10545,NaN,LRAD Corporation,lrad,/company/american-technology-corp,semiconductor,ipo,1980-01-01,NaN,lradx.com,http://www.lradx.com,LRADX,http://s3.amazonaws.com/crunchbase_prod_assets...,300.0,82.0,NaN,sound technologies and acoustic products,"LRAD Corporation, formerly American Technology...",NaN,USA,CA,San Diego,San Diego,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-08-17,2011-08-17,1.0,2.0,NaN,2008-09-05 00:54:35,2013-07-04 21:40:04,20986,24611,HQ,San Diego,15378 Avenue of Science,Suite 100,San Diego,92128,CA,USA,NaN,NaN,NaN,NaN,10521,2011-02-08,other,LRAD Corporation Receives $4.3 Million Through...,http://www.marketwire.com/press-release/LRAD-C...,LRAD Corporation Receives $4.3 Million Through...,2011-02-08 17:50:10,2011-02-08 17:50:10,440,489,NaN,USD,NaN,NaN,NaN,NASDAQ:LRAD,NaN,NaN,2010-10-08 03:40:14,2010-10-08 03:40:14
12,c:10545,Company,10545,NaN,LRAD Corporation,lrad,/company/american-technology-corp,semiconductor,ipo,1980-01-01,NaN,lradx.com,http://www.lradx.com,LRADX,http://s3.amazonaws.com/crunchbase_prod_assets...,300.0,82.0,NaN,sound technologies and acoustic products,"LRAD Corporation, formerly American Technology...",NaN,USA,CA,San Diego,San Diego,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-08-17,2011-08-17,1.0,2.0,NaN,2008-09-05 00:54:35,2013-07-04 21:40:04,20986,24611,HQ,San Diego,15378 Avenue of Science,Suite 100,San Diego,92128,CA,USA,NaN,NaN,NaN,NaN,10856,2011-02-17,other,"LRAD Corporation (NASDAQ: LRAD), the world lea...",http://www.earthtimes.org/articles/press/from-...,"LRAD Corporation Receives $800,000 in LRAD(R) ...",2011-02-18 11:36:15,2011-02-18 11:36:15,440,489,NaN,USD,NaN,NaN,NaN,NASDAQ:LRAD,NaN,NaN,2010-10-08 03:40:14,2010-10-08 03:40:14
13,c:10545,Company,10545,NaN,LRAD Corporation,lrad,/company/american-technology-corp,semiconductor,ipo,1980-01-01,NaN,lradx.com,http://www.lradx.com,LRADX,http://s3.amazonaws.com/crunchbase_prod_assets...,300.0,82.0,NaN,sound technologies and acoustic products,"LRAD Corporation, formerly American Technology...",NaN,USA,CA,San Diego,San Diego,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-08-17,2011-08-17,1.0,2.0,NaN,2008-09-05 00:54:35,2013-07-04 21:40:04,20986,24611,HQ,San Diego,15378 Avenue of Science,Suite 100,San Diego,92128,CA,USA,NaN,NaN,NaN,NaN,11170,2011-03-02,other,LRAD Corporation to Present at Roth Orange Cou...,http://www.marketwire.com/press-release/LRAD-C...,LRAD Corporation to Present at Roth Orange Cou...,2011-03-03 07:27:17,2011-03-03 07:27:17,440,489,NaN,USD,NaN,NaN,NaN,NASDAQ:LRAD,NaN,NaN,2010-10-08 03:40:14,2010-10-08 03:40:14
14,c:10545,Company,10545,NaN,LRAD Corporation,lrad,/company/american-technology-corp,semiconductor,ipo,1980-01-01,NaN,lradx.com,http://www.lradx.com,LRADX,http://s3.amazonaws.com/crunchbase_prod_assets...,300.0,82.0,NaN,sound technologies and acoustic products,"LRAD Corporation, formerly American Technology...",NaN,USA,CA,San Diego,San Diego,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-08-17,2011-08-17,1.0,2.0,NaN,2008-09-05 00:54:35,2013-07-04 21:40:04,20986,24611,HQ,San Diego,15378 Avenue of Science,Suite 100,San Diego,92128,CA,USA,NaN,NaN,NaN,NaN,15009,2011-08-17,other,LRAD Corporation Announces $1.5 Million in LRA...,http://www.freshnews.com/news/535581/lrad-corp...,LRAD Corporation Announces $1.5 Million in LRA...,2011-08-18 04:30:05,2011-08-18 04:30:05,440,489,NaN,USD,NaN,NaN,NaN,NASDAQ:LRAD,NaN,NaN,2010-10-08 03:40:14,2010-10-08 03:40:14
15,c:10614,Company,10614,NaN,Inuvo,inuvo,/company/inuvo,advertising,ipo,2009-08-01,NaN,inuvo.com,http://www.inuvo.com,Inuvo,http://s3.amazonaws.com/crunchbase_prod_assets...,2208.0,870.0,NaN,Performance-based advertising,One billion dollars!\r\n\r\nThat's the amount ...,"affiliate-marketing, search, click-fraud-techn...",USA,FL,Clearwater,Tampa,NaN,NaN,NaN,NaN,2010-01-19,2010-01-19,1.0,4.200000e+06,2010-06-01,2012-03-01,3.0,17.0,NaN,2008-09-06 02:48:32,2013-07-04 21:46:23,9772,11735,"Clearwater, FL",Tampa,15500 Lightwave Dr.,Suite 300,Clearwater,33760,FL,USA,27.913011,-82.702449,NaN,NaN,7682,2008-11-17,other,"Rich Howe, CEO",http://inuvo.com/management,"Announced Hire of New CEO, Rich Howe",2010-10-14 18:34:10,2010-10-15 00:19:59,201,231,3.000000e+07,USD,NaN,NaN,2010-02-10,NYSE:INUV,NaN,NaN,2009-11-30 04:33:12,2010-02-10 23:45:04
16,c:10614,Company,10614,NaN,Inuvo,inuvo,/company/inuvo,advertising,ipo,2009-08-01,NaN,inuvo.com,http://www.inuvo.com,Inuvo,http://s3.amazonaws.com/crunchbase_prod_assets...,2208.0,870.0,NaN,Performance-based advertising,One billion dollars!\r\n\r\nThat's the amount ...,"affiliate-marketing, search, click-fraud-techn...",USA,FL,Clearwater,Tampa,NaN,NaN,NaN,NaN,2010-01-19,2010-01-19,1.0,4.200000e+06,2010-06-01,2012-03-01,3.0,17.0,NaN,2008-09-06 02:48:32,2013-07-04 21:46:23,9772,11735,"Clearwater, FL",Tampa,15500 Lightwave Dr.,Suite 300,Clearwater,33760,FL,USA,27.913011,-82.702449,NaN,NaN,7683,2010-06-01,other,"Wallace Ruiz, CFO",http://inuvo.com/management,"Announced Hire of New CFO, Wallace Ruiz",2010-10-14 18:35:38,2010-10-15 00:19:48,201,231,3.000000e+07,USD,NaN,NaN,2010-02-10,NYSE:INUV,NaN,NaN,2009-11-30 04:33:12,2010-02-10 23:45:04
17,c:10614,Company,10614,NaN,Inuvo,inuvo,/company/inuvo,advertising,ipo,2009-08-01,NaN,inuvo.com,http://www.inuvo.com,Inuvo,http://s3.amazonaws.com/crunchbase_prod_assets...,2208.0,870.0,NaN,Performance-based advertising,One billion dollars!\r\n\r\nThat's the amount ...,"affiliate-marketing, search, click-fraud-techn...",USA,FL,Clearwater,Tampa,NaN,NaN,NaN,NaN,2010-01-19,2010-01-19,1.0,4.200000e+06,2010-06-01,2012-03-01,3.0,17.0,NaN,2008-09-06 02:48:32,2013-07-04 21:46:23,9772,11735,"Clearwater, FL",Tampa,15500 Lightwave Dr.,Suite 300,Clearwater,33760,FL,USA,27.913011,-82.702449,NaN,NaN,12473,2008-11-01,other,Inuvo hires Richard Howe as CEO,http://www.review.net/section/detail/digital-d...,Digital do Over,2011-04-28 21:29:22,2011-05-05 01:38:41,201,231,3.000000e+07,USD,NaN,NaN,2010-02-10,NYSE:INUV,NaN,NaN,2009-11-30 04:33:12,2010-02-10 23:45:04
18,c:10614,Company,10614,NaN,Inuvo,inuvo,/company/inuvo,advertising,ipo,2009-08-01,NaN,inuvo.com,http://www.inuvo.com,Inuvo,http://s3.amazonaws.com/crunchbase_prod_assets...,2208.0,870.0,NaN,Performance-based advertising,One billion dollars!\r\n\r\nThat's the amount ...,"affiliate-marketing, search, click-fraud-techn...",USA,FL,Clearwater,Tampa,NaN,NaN,NaN,NaN,2010-01-19,2010-01-19,1.0,4.200000e+06,2010-06-01,2012-03-01,3.0,17.0,NaN,2008-09-06 02:48:32,2013-07-04 21:46:23,9772,11735,"Clearwater, FL",Tampa,15500 Lightwave Dr.,Suite 300,Clearwater,33760,FL,USA,27.913011,-82.702449,NaN,NaN,12474,2009-02-01,other,Inuvo divests of non core business,http://sec.gov/Archives/edgar/data/829323/0001...,SEC Filing,2011-04-28 21:29:22,2011-05-05 01:38:41,201,231,3.000000e+07,USD,NaN,NaN,2010-02-10,NYSE:INUV,NaN,NaN,2009-11-30 04:33:12,2010-02-10 23:45:04
19,c:1063,Company,1063,NaN,YuMe,yume,/company/yume,advertising,ipo,2004-01-01,NaN,yume.com,http://www.yume.com,YuMeVideo,http://s3.amazonaws.com/crunchbase_prod_assets...,246.0,99.0,YuMe provides digital video advertising soluti...,Video Advertising,"YuMe, Inc. is a leading provider of digital vi...","video-advertising, advertising",USA,CA,Redwood City,SF Bay,NaN,NaN,NaN,NaN,2006-08-01,2012-05-23,8.0,7.290000e+07,2010-10-13,2013-03-01,4.0,28.0,initial-importer,2007-10-16 00:20:55,2013-09-12 02:45:30,887,1045,YuMe Headquarterts,SF Bay,1204 Middlefield Road,NaN,Redwood City,94063,CA,USA,37.476479,-122.221717,NaN,NaN,342,2008-06-16,other,"YuMe to Provide Ad Network Management, Reporti...",NaN,"YuMe to Provide Ad Network Management, Reporti...",2008-08-11 22:56:47,2008-08-11 23:16:21,924,1002,NaN,USD,65000000.0,USD,2013-07-02,NYSE:YUME,http://techcrunch.com/2013/07/02/yume-ipo/,Main Event Page news Comment 0 inShare9 Anothe...,2013-07-03 00:00:56,2013-07-03 00:00:56
20,c:1063,Company,1063,NaN,YuMe,yume,/company/yume,advertising,ipo,2004-01-01,NaN,yume.com,http://www.yume.com,YuMeVideo,http://s3.amazonaws.com/crunchbase_prod_assets...,246.0,99.0,YuMe provides digital video advertising soluti...,Video Advertising,"YuMe, Inc. is a leading provider of digital vi...","video-advertising, advertising",USA,CA,Redwood City,SF Bay,NaN,NaN,NaN,NaN,2006-08-01,2012-05-23,8.0,7.290000e+07,2010-10-13,2013-03-01,4.0,28.0,initial-importer,2007-10-16 00:20:55,2013-09-12 02:45:30,887,1045,YuMe Headquarterts,SF Bay,1204 Middlefield Road,NaN,Redwood City,94063,CA,USA,37.476479,-122.221717,NaN,NaN,345,2008-08-11,other,YuMe Brings in Michael Mathieu as New CEO,http://www.techcrunch.com/2008/08/11/new-ceo-f...,New CEO For YuMe,2008-08-12 01:45:34,2008-08-12 01:45:56,924,1002,NaN,USD,65000000.0,USD,2013-07-02,NYSE:YUME,http://techcrunch.com/2013/07/02/yume-ipo/,Main Event Page news Comment 0 inShare9 Anothe...,2013-07-03 00:00:56,2013-07-03 00:00:56
21,c:1063,Company,1063,NaN,YuMe,yume,/company/yume,advertising,ipo,2004-01-01,NaN,yume.com,http://www.yume.com,YuMeVideo,http://s3.amazonaws.com/crunchbase_prod_assets...,246.0,99.0,YuMe provides digital video advertising soluti...,Video Advertising,"YuMe, Inc. is a leading provider of digital vi...","video-advertising, advertising",USA,CA,Redwood City,SF Bay,NaN,NaN,NaN,NaN,2006-08-01,2012-05-23,8.0,7.290000e+07,2010-10-13,2013-03-01,4.0,28.0,initial-importer,2007-10-16 00:20:55,2013-09-12 02:45:30,887,1045,YuMe Headquarterts,SF Bay,1204 Middlefield Road,NaN,Redwood City,94063,CA,USA,37.476479,-122.221717,NaN,NaN,7705,2010-01-25,other,YuMe Appoints Scot McLernon as Chief Revenue O...,http://www.nytimes.com/2010/01/25/business/med...,"Accounts, People & Miscellany",2010-10-15 19:51:06,2010-10-15 20:29:42,924,1002,NaN,USD,65000000.0,USD,2013-07-02,NYSE:YUME,http://techcrunch.com/2013/07/02/yume-ipo/,Main Event Page news Comment 0 inShare9 Anothe...,2013-07-03 00:00:56,2013-07-03 00:00:56

In [60]:
df_companies_db= pd.DataFrame([df_companies['name'].unique() , df_peep['full_name'].unique() , df_peep['affiliation_name'].unique()]).transpose()
df_companies_db.head()

                 0               1             2
0         Attunity     Ben Elowitz     Blue Nile
1  Thomson Reuters  Kevin Flaherty      Wetpaint
2          Hitachi       Ian Wenig          Zoho
3     Tremor Video      Kevin Rose  i/o Ventures
4         Bankrate     Jay Adelson          Digg

In [30]:
df_companies.nunique()

object_id                   591
entity_type                   1
entity_id                   591
parent_id                     0
name                        591
normalized_name             591
permalink                   591
category_code                32
status                        2
founded_at                  142
closed_at                     0
domain                      590
homepage_url                590
twitter_username            348
logo_url                    587
logo_width                  272
logo_height                 177
short_description            50
description_x               265
overview                    590
tag_list                    157
country_code_x               21
state_code_x                 35
city_x                      294
region_x                    151
first_investment_at         137
last_investment_at          132
investment_rounds            20
invested_companies           19
first_funding_at            251
                           ...
address1                    826
address2                    271
city_y                      411
zip_code                    599
state_code_y                 39
country_code_y               44
latitude                    317
longitude                   317
created_at_y_x                0
updated_at_y_x                0
id_x                       1879
milestone_at                887
milestone_code                1
description                1862
source_url_x               1769
source_description_x       1677
created_at_x_y             1728
updated_at_x_y             1699
id_y                        592
ipo_id                      592
valuation_amount             62
valuation_currency_code       3
raised_amount                55
raised_currency_code          4
public_at                   271
stock_symbol                592
source_url_y                 87
source_description_y         78
created_at_y_y              592
updated_at_y_y              592
Length: 74, dtype: int64

## What type of info we have

In [31]:
pd.set_option('display.max_columns', 500)

In [32]:
df_companies.head(5)

,object_id,entity_type,entity_id,parent_id,name,normalized_name,permalink,category_code,status,founded_at,closed_at,domain,homepage_url,twitter_username,logo_url,logo_width,logo_height,short_description,description_x,overview,tag_list,country_code_x,state_code_x,city_x,region_x,first_investment_at,last_investment_at,investment_rounds,invested_companies,first_funding_at,last_funding_at,funding_rounds,funding_total_usd,first_milestone_at,last_milestone_at,milestones,relationships,created_by,created_at_x_x,updated_at_x_x,id,office_id,description_y,region_y,address1,address2,city_y,zip_code,state_code_y,country_code_y,latitude,longitude,created_at_y_x,updated_at_y_x,id_x,milestone_at,milestone_code,description,source_url_x,source_description_x,created_at_x_y,updated_at_x_y,id_y,ipo_id,valuation_amount,valuation_currency_code,raised_amount,raised_currency_code,public_at,stock_symbol,source_url_y,source_description_y,created_at_y_y,updated_at_y_y
0,c:100844,Company,100844,NaN,Attunity,attunity,/company/attunity,software,ipo,NaN,NaN,attunity.com,http://www.attunity.com,attunity,http://s3.amazonaws.com/crunchbase_prod_assets...,1635.0,379.0,Attunity provides information-availability sof...,NaN,Attunity is a leading provider of information ...,NaN,USA,MA,Burlington,Boston,NaN,NaN,NaN,NaN,2004-06-01,2011-09-21,4.0,10500000.0,2012-02-14,2012-02-14,1.0,1.0,timircha,2011-09-07 13:47:49,2013-07-16 15:49:48,52712,60335,NaN,Boston,70 Blanchard Road,NaN,Burlington,01803,MA,USA,NaN,NaN,NaN,NaN,18406,2012-02-14,other,Attunity gets $1M license from mystery cable c...,http://www.masshightech.com/stories/2012/02/13...,Attunity gets $1M license from mystery cable c...,2012-02-15 02:39:55,2012-02-15 02:39:55,941,1022,NaN,USD,NaN,USD,2007-08-01,ATTU,http://www.attunity.com/news/attunity-receives...,ATTUNITY receives Nasdaq,2013-07-16 16:05:56,2013-07-16 17:51:40
1,c:10106,Company,10106,NaN,Thomson Reuters,thomson reuters,/company/thomson-reuters,public_relations,ipo,2008-04-17,NaN,thomsonreuters.com,http://thomsonreuters.com,ThomsonReuters,http://s3.amazonaws.com/crunchbase_prod_assets...,680.0,680.0,NaN,Intelligent Information Provider,Thomson Reuters is the world's leading source ...,NaN,USA,NY,New York,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010-06-08,2013-04-29,4.0,100.0,NaN,2008-08-26 07:43:06,2012-08-09 13:33:58,78740,91411,NaN,New York,3 Times Square,NaN,New York,10036,NY,USA,40.756432,-73.987185,NaN,NaN,5421,2010-06-08,other,Thomson Reuters has acquired UAE legislation L...,http://fusiondiginet.com/2010/06/08/thomson-re...,Thomson Reuters has acquired UAE legislation L...,2010-07-08 12:35:06,2010-07-08 12:35:06,1018,1110,NaN,USD,NaN,USD,2002-06-21,NYSE:TRI,NaN,NaN,2013-08-26 10:53:26,2013-08-26 20:14:31
2,c:10222,Company,10222,NaN,Hitachi,hitachi,/company/hitachi,public_relations,ipo,NaN,NaN,hitachi.com,http://www.hitachi.com,NaN,http://s3.amazonaws.com/crunchbase_prod_assets...,155.0,82.0,NaN,NaN,"Since its founding in 1910, Hitachi has respon...",NaN,JPN,NaN,Tokyo,Tokyo,2013-11-03,2013-11-03,1.0,1.0,NaN,NaN,NaN,NaN,2009-12-09,2013-08-23,3.0,44.0,NaN,2008-08-27 21:43:47,2013-11-25 08:36:12,61291,71209,NaN,Tokyo,"6-6, Marunouchi 1-chome",Chiyoda-ku,Tokyo,100-8280,NaN,JPN,NaN,NaN,NaN,NaN,2885,2009-12-09,other,Hitachi Acquires Software Assets Related to Ne...,http://www.hitachi.com/New/cnews/091209.html,Hitachi Acquires Software Assets Related to Ne...,2010-01-25 12:08:01,2010-01-25 12:09:07,741,804,NaN,USD,NaN,USD,1978-01-13,NYSE:HIT,NaN,NaN,2012-04-12 04:27:30,2012-04-12 04:27:30
3,c:104377,Company,104377,NaN,Tremor Video,tremor video,/company/tremor-video,advertising,ipo,2005-01-01,NaN,tremorvideo.com,http://tremorvideo.com,tremorvideo,http://s3.amazonaws.com/crunchbase_prod_assets...,201.0,75.0,NaN,NaN,Tremor Video is a digital video technology com...,NaN,USA,NY,New York,New York,NaN,NaN,NaN,NaN,2006-03-01,2011-09-12,8.0,116400000.0,2011-12-01,2013-05-23,3.0,24.0,timircha,2011-09-13 12:12:56,2013-03-20 01:58:12,52987,60659,NaN,New York,53 West 23rd Street,12th Floor,New York,10010,NY,USA,NaN,NaN,NaN,NaN,17734,2012-01-20,other,Tremor Video Acquires,http://techcrunch.com/2012/01/20/tremor-video-...,Tremor Video Acquires,2012-01-21 02:53:42,2012-01-21 02:53:42,850,923,NaN,USD,75000000.0,USD,2013-06-27,NYSE:TRMR,http://www.bizjournals.com/newyork/news/2013/0...,Tremor Video,2013-05-24 05:04:39,2013-07-18 18:03:13
4,c:104377,Company,104377,NaN,Tremor Video,tremor video,/company/tremor-video,advertising,ipo,2005-01-01,NaN,tremorvideo.com,http://tremorvideo.com,tremorvideo,http://s3.amazonaws.com/crunchbase_prod_assets...,201.0,75.0,NaN,NaN,Tremor Video is a digital video technology com...,NaN,USA,NY,New York,New York,NaN,NaN,NaN,NaN,2006-03-01,2011-09-12,8.0,116400000.0,2011-12-01,2013-05-23,3.0,24.0,timircha,2011-09-13 12:12:56,2013-03-20 01:58:12,58252,67339,NaN,Toronto,NaN,NaN,Toronto,NaN,NaN,CAN,NaN,NaN,NaN,NaN,17734,2012-01-20,other,Tremor Video Acquires,http://techcrunch.com/2012/01/20/tremor-video-...,Tremor Video Acquires,2012-01-21 02:53:42,2012-01-21 02:53:42,850,923,NaN,USD,75000000.0,USD,2013-06-27,NYSE:TRMR,http://www.bizjournals.com/newyork/news/2013/0...,Tremor Video,2013-05-24 05:04:39,2013-07-18 18:03:13

In [33]:
companies_info_list = list(df_companies.columns)
companies_info_list
#we need : 
companies_needed_info = ['object_id', 'entity_type', 'name', 'category_code','status', 'founded_at', 'closed_at', 'overview','country_code','state_code', 'city_x','region_x', 'first_investment_at', 'last_investment_at', 'investment_rounds', 'invested_companies', 'first_funding_at', 'last_funding_at', 'funding_rounds', 'funding_total_usd', 'first_milestone_at', 'last_milestone_at','created_by', 'created_at', 'valuation_amount', 'valuation_currency_code','raised_amount', 'raised_currency_code', 'public_at']

In [34]:
df_peep.head(3)

,id_x,object_id,first_name,last_name,birthplace,affiliation_name,id_y,degree_type,subject,institution,graduated_at,created_at,updated_at,full_name
0,1,p:2,Ben,Elowitz,NaN,Blue Nile,699,BS,Electrical Engineering/Computer Science,"University of California, Berkeley",1994-01-01,2008-05-06 00:05:48,2008-05-06 00:05:48,Ben Elowitz
1,1,p:2,Ben,Elowitz,NaN,Blue Nile,700,BS,Applied Mathematics,"University of California, Berkeley",1994-01-01,2008-05-06 00:06:10,2008-05-06 00:06:10,Ben Elowitz
2,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38,Kevin Flaherty

In [50]:
people_info_list= list(df_peep.columns)
people_needed_info = ['full_name', 'subject', 'object_id', 'relationship_object_id']

In [51]:
df_people= pd.merge(df_peep, df_relationships, on='object_id')

In [52]:
df_people

,id_x,object_id,first_name,last_name,birthplace,affiliation_name,id_y,degree_type,subject,institution,graduated_at,created_at_x,updated_at_x,full_name,id,relationship_id,relationship_object_id,start_at,end_at,is_past,sequence,title,created_at_y,updated_at_y
0,1,p:2,Ben,Elowitz,NaN,Blue Nile,699,BS,Electrical Engineering/Computer Science,"University of California, Berkeley",1994-01-01,2008-05-06 00:05:48,2008-05-06 00:05:48,Ben Elowitz,1,1,c:1,NaN,NaN,0,8,Co-Founder/CEO/Board of Directors,2007-05-25 07:03:54,2013-06-03 09:58:46
1,1,p:2,Ben,Elowitz,NaN,Blue Nile,699,BS,Electrical Engineering/Computer Science,"University of California, Berkeley",1994-01-01,2008-05-06 00:05:48,2008-05-06 00:05:48,Ben Elowitz,11366,11366,c:4993,NaN,NaN,1,6,Co-founder & VP,2008-05-06 00:04:18,2013-06-02 16:56:52
2,1,p:2,Ben,Elowitz,NaN,Blue Nile,699,BS,Electrical Engineering/Computer Science,"University of California, Berkeley",1994-01-01,2008-05-06 00:05:48,2008-05-06 00:05:48,Ben Elowitz,11367,11367,c:233024,NaN,NaN,1,2,Business Development,2008-05-06 00:04:18,2013-06-02 16:56:52
3,1,p:2,Ben,Elowitz,NaN,Blue Nile,699,BS,Electrical Engineering/Computer Science,"University of California, Berkeley",1994-01-01,2008-05-06 00:05:48,2008-05-06 00:05:48,Ben Elowitz,22537,22537,f:1017,NaN,NaN,0,7,Limited Partner,2008-10-07 02:23:04,2010-10-08 21:02:10
4,1,p:2,Ben,Elowitz,NaN,Blue Nile,699,BS,Electrical Engineering/Computer Science,"University of California, Berkeley",1994-01-01,2008-05-06 00:05:48,2008-05-06 00:05:48,Ben Elowitz,112873,112873,c:18661,NaN,NaN,1,3,Consultant,2011-05-11 01:24:28,2011-05-11 01:24:28
5,1,p:2,Ben,Elowitz,NaN,Blue Nile,699,BS,Electrical Engineering/Computer Science,"University of California, Berkeley",1994-01-01,2008-05-06 00:05:48,2008-05-06 00:05:48,Ben Elowitz,260915,260915,c:537,2002-01-01,2002-01-01,1,1,Consultant,2013-06-02 16:56:52,2013-06-02 16:56:52
6,1,p:2,Ben,Elowitz,NaN,Blue Nile,699,BS,Electrical Engineering/Computer Science,"University of California, Berkeley",1994-01-01,2008-05-06 00:05:48,2008-05-06 00:05:48,Ben Elowitz,260917,260917,c:2361,NaN,NaN,1,4,Consultant,2013-06-02 16:56:52,2013-06-02 16:56:52
7,1,p:2,Ben,Elowitz,NaN,Blue Nile,699,BS,Electrical Engineering/Computer Science,"University of California, Berkeley",1994-01-01,2008-05-06 00:05:48,2008-05-06 00:05:48,Ben Elowitz,414818,414818,c:268504,NaN,NaN,1,5,Consultant,2013-10-01 00:48:10,2013-10-01 00:48:10
8,1,p:2,Ben,Elowitz,NaN,Blue Nile,700,BS,Applied Mathematics,"University of California, Berkeley",1994-01-01,2008-05-06 00:06:10,2008-05-06 00:06:10,Ben Elowitz,1,1,c:1,NaN,NaN,0,8,Co-Founder/CEO/Board of Directors,2007-05-25 07:03:54,2013-06-03 09:58:46
9,1,p:2,Ben,Elowitz,NaN,Blue Nile,700,BS,Applied Mathematics,"University of California, Berkeley",1994-01-01,2008-05-06 00:06:10,2008-05-06 00:06:10,Ben Elowitz,11366,11366,c:4993,NaN,NaN,1,6,Co-founder & VP,2008-05-06 00:04:18,2013-06-02 16:56:52
10,1,p:2,Ben,Elowitz,NaN,Blue Nile,700,BS,Applied Mathematics,"University of California, Berkeley",1994-01-01,2008-05-06 00:06:10,2008-05-06 00:06:10,Ben Elowitz,11367,11367,c:233024,NaN,NaN,1,2,Business Development,2008-05-06 00:04:18,2013-06-02 16:56:52
11,1,p:2,Ben,Elowitz,NaN,Blue Nile,700,BS,Applied Mathematics,"University of California, Berkeley",1994-01-01,2008-05-06 00:06:10,2008-05-06 00:06:10,Ben Elowitz,22537,22537,f:1017,NaN,NaN,0,7,Limited Partner,2008-10-07 02:23:04,2010-10-08 21:02:10
12,1,p:2,Ben,Elowitz,NaN,Blue Nile,700,BS,Applied Mathematics,"University of California, Berkeley",1994-01-01,2008-05-06 00:06:10,2008-05-06 00:06:10,Ben Elowitz,112873,112873,c:18661,NaN,NaN,1,3,Consultant,2011-05-11 01:24:28,2011-05-11 01:24:28
13,1,p:2,Ben,Elowitz,NaN,Blue Nile,700,BS,Applied Mathematics,"University of California, Berkeley",1994-01-01,2008-05-06 00:06:10,2008-05-06 00:06:10,Ben Elowitz,260915,260915,c:537,2002-01-01,2002-01-01,1,1,Consultant,2013-06-02 16:56:52,2013-06-02 16:56:52
14,1,p:2,Ben,Elowitz,NaN,Blue Nile,700,BS,Applied Mathematics,"University of California, Berkeley",1994-01-01,2008-05-06 00:06:10,2008-05-06 00:06:10,Ben Elowitz,260917,260917,c:2361,NaN,NaN,1,4,Consultant,2013-06-02 16:56:52,2013-06-02 16:56:52
15,1,p:2,Ben,Elowitz,NaN,Blue Nile,700,BS,Applied Mathematics,"University of California, Berkeley",1994-01-01,2008-05-06 00:06:10,2008-05-06 00:06:10,Ben Elowitz,414818,414818,c:268504,NaN,NaN,1,5,Consultant,2013-10-01 00:48:10,2013-10-01 00:48:10
16,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38,Kevin Flaherty,2,2,c:1,NaN,NaN,1,279242,VP Marketing,2007-05-25 07:04:16,2010-05-21 16:31:34
17,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38,Kevin Flaherty,22539,22539,f:1017,NaN,NaN,0,279243,Limited Partner,2008-10-07 02:23:04,2010-10-08 21:02:10
18,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38,Kevin Flaherty,80751,80751,c:28294,NaN,NaN,0,279244,NaN,2010-08-04 22:10:45,2013-11-21 09:43:39
19,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38,Kevin Flaherty,97106,97106,c:45209,NaN,NaN,0,279245,NaN,2011-01-04 18:50:26,2013-11-21 09:43:39
20,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38,Kevin Flaherty,104984,104984,c:60421,NaN,NaN,0,279246,NaN,2011-03-12 00:26:38,2013-02-02 04:53:04
21,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38,Kevin Flaherty,261486,261486,c:174210,NaN,NaN,0,279247,NaN,2013-06-03 10:29:08,2013-11-21 09:43:39
22,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38,Kevin Flaherty,261487,261487,c:220488,2001-01-01,2005-01-01,1,279241,NaN,2013-06-03 10:29:08,2013-11-21 09:43:39
23,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38,Kevin Flaherty,261488,261488,c:196560,2000-01-01,2001-01-01,1,1,NaN,2013-06-03 10:29:08,2013-11-21 09:43:40
24,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38,Kevin Flaherty,261489,261489,c:200709,1997-01-01,2000-01-01,1,279240,NaN,2013-06-03 10:29:08,2013-11-21 09:43:40
25,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38,Kevin Flaherty,261490,261490,c:220489,1993-01-01,1995-01-01,1,279239,NaN,2013-06-03 10:29:08,2013-11-21 09:43:40
26,2,p:3,Kevin,Flaherty,NaN,Wetpaint,706,BBA,NaN,Washington University in St Louis,NaN,2008-05-07 19:40:58,2013-11-21 09:43:38,Kevin Flaherty,380196,380196,f:1017,NaN,NaN,0,279248,mentor,2013-09-03 09:14:34,2013-09-03 09:14:34
27,2,p:3,Kevin,Flaherty,NaN,Wetpaint,707,MBA,NaN,Indiana University,NaN,2008-05-07 19:41:24,2013-11-21 09:43:38,Kevin Flaherty,2,2,c:1,NaN,NaN,1,279242,VP Marketing,2007-05-25 07:04:16,2010-05-21 16:31:34
28,2,p:3,Kevin,Flaherty,NaN,Wetpaint,707,MBA,NaN,Indiana University,NaN,2008-05-07 19:41:24,2013-11-21 09:43:38,Kevin Flaherty,22539,22539,f:1017,NaN,NaN,0,279243,Limited Partner,2008-10-07 02:23:04,2010-10-08 21:02:10
29,2,p:3,Kevin,Flaherty,NaN,Wetpaint,707,MBA,NaN,Indiana University,NaN,2008-05-07 19:41:24,2013-11-21 09:43:38,Kevin Flaherty,80751,80751,c:28294,NaN,NaN,0,279244,NaN,2010-08-04 22:10:45,2013-11-21 09:43:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390888,226651,p:268524,James,Trueman,NaN,Unaffiliated,109604,Masters,Business Administration,"Wharton School of Business , University of Pen...",NaN,2013-12-12 14:22:33,2013-12-12 14:22:33,James Trueman,480889,480889,c:286211,NaN,NaN,1,1,Managing Partner,2013-12-12 14:23:11,2013-12-12 14:23:11
390889,226651,p:268524,James,Trueman,NaN,Unaffiliated,109604,Masters,Business Administration,"Wharton School of Business , University of Pen...",NaN,2013-12-12 14:22:33,2013-12-12 14:22:33,James Trueman,480890,480890,c:286212,NaN,NaN,1,2,Managing Partner,2013-12-12 14:23:33,2013-12-12 14:23:33
390890,226651,p:268524,James,Trueman,NaN,Unaffiliated,109604,Masters,Business Administration,"Wharton School of Business , University of Pen...",NaN,2013-12-12 14:22:33,2013-12-12 14:22:33,James Trueman,480891,480891,c:4715,NaN,NaN,1,3,Engagement Manager,2013-12-12 14:23:52,2013-12-12 14:23:52
390891,226651,p:268524,James,Trueman,NaN,Unaffiliated,109604,Masters,Business Administration,"Wharton School of Business , University of Pen...",NaN,2013-12-12 14:22:33,2013-12-12 14:22:33,James Trueman,480892,480892,c:4715,NaN,NaN,1,4,Independent Management Consultant and An Engag...,2013-12-12 14:24:13,2013-12-12 14:24:13
390892,226651,p:268524,James,Trueman,NaN,Unaffiliated,109604,Masters,Business Administration,"Wharton School of Business , University of Pen...",NaN,2013-12-12 14:22:33,2013-12-12 14:22:33,James Trueman,480893,480893,c:286213,NaN,NaN,1,5,Chief Executive Officer,2013-12-12 14:24:28,2013-12-12 14:24:28
390893,226654,p:268527,Harry,Wei,NaN,Unaffiliated,109607,MS & BS,Engineering,South China University of Technology,NaN,2013-12-12 14:31:21,2013-12-12 14:31:21,Harry Wei,480760,480760,c:39172,2013-10-01,NaN,0,273048,Senior Director,2013-12-12 11:37:02,2013-12-12 14:33:37
390894,226654,p:268527,Harry,Wei,NaN,Unaffiliated,109607,MS & BS,Engineering,South China University of Technology,NaN,2013-12-12 14:31:21,2013-12-12 14:31:21,Harry Wei,480901,480901,c:39172,2012-04-01,2013-10-01,1,273047,"Director, Business Development",2013-12-12 14:34:17,2013-12-12 14:34:17
390895,226654,p:268527,Harry,Wei,NaN,Unaffiliated,109607,MS & BS,Engineering,South China University of Technology,NaN,2013-12-12 14:31:21,2013-12-12 14:31:21,Harry Wei,480902,480902,c:286217,2010-09-01,2012-04-01,1,1,"Sr. Manager, IP Analytics",2013-12-12 14:34:55,2013-12-12 14:34:55
390896,226654,p:268527,Harry,Wei,NaN,Unaffiliated,109607,MS & BS,Engineering,South China University of Technology,NaN,2013-12-12 14:31:21,2013-12-12 14:31:21,Harry Wei,480903,480903,c:286218,2005-01-01,2010-01-01,1,1,Sr. Consultant/Patent Agent,2013-12-12 14:35:35,2013-12-12 14:35:35
390897,226654,p:268527,Harry,Wei,NaN,Unaffiliated,109608,PhD,Engineering,Clarkson University,NaN,2013-12-12 14:31:48,2013-12-12 14:31:48,Harry Wei,480760,480760,c:39172,2013-10-01,NaN,0,273048,Senior Director,2013-12-12 11:37:02,2013-12-12 14:33:37
390898,226654,p:268527,Harry,Wei,NaN,Unaffiliated,109608,PhD,Engineering,Clarkson University,NaN,2013-12-12 14:31:48,2013-12-12 14:31:48,Harry Wei,480901,480901,c:39172,2012-04-01,2013-10-01,1,273047,"Director, Business Development",2013-12-12 14:34:17,2013-12-12 14:34:17
390899,226654,p:268527,Harry,Wei,NaN,Unaffiliated,109608,PhD,Engineering,Clarkson University,NaN,2013-12-12 14:31:48,2013-12-12 14:31:48,Harry Wei,480902,480902,c:286217,2010-09-01,2012-04-01,1,1,"Sr. Manager, IP Analytics",2013-12-12 14:34:55,2013-12-12 14:34:55
390900,226654,p:268527,Harry,Wei,NaN,Unaffiliated,109608,PhD,Engineering,Clarkson University,NaN,2013-12-12 14:31:48,2013-12-12 14:31:48,Harry Wei,480903,480903,c:286218,2005-01-01,2010-01-01,1,1,Sr. Consultant/Patent Agent,2013-12-12 14:35:35,2013-12-12 14:35:35
390901,226655,p:268528,Edward,J. Treska,NaN,Unaffiliated,109609,B.S.,Electrical Engineering,Colorado State University,NaN,2013-12-12 14:38:15,2013-12-12 14:38:15,Edward J. Treska,480761,480761,c:39172,NaN,NaN,0,273050,"""Senior Vice President General Counsel of Acac...",2013-12-12 11:37:18,2013-12-12 11:37:18
390902,226655,p:268528,Edward,J. Treska,NaN,Unaffiliated,109609,B.S.,Electrical Engineering,Colorado State University,NaN,2013-12-12 14:38:15,2013-12-12 14:38:15,Edward J. Treska,480907,480907,c:286152,NaN,NaN,1,273049,Vice President,2013-12-12 14:39:36,2013-12-12 14:39:36
390903,226655,p:268528,Edward,J. Treska,NaN,Unaffiliated,109609,B.S.,Electrical Engineering,Colorado State University,NaN,2013-12-12 14:38:15,2013-12-12 14:38:15,Edward J. Treska,480908,480908,c:286220,NaN,NaN,1,1,"General Counsel, Director of Patents and Licen...",2013-12-12 14:39:48,2013-12-12 14:39:48
390904,226655,p:268528,Edward,J. Treska,NaN,Unaffiliated,109609,B.S.,Electrical Engineering,Colorado State University,NaN,2013-12-12 14:38:15,2013-12-12 14:38:15,Edward J. Treska,480909,480909,c:286221,NaN,NaN,1,1,Design Engineer,2013-12-12 14:40:04,2013-12-12 14:40:04
390905,226655,p:268528,Edward,J. Treska,NaN,Unaffiliated,109610,J.D.,NaN,University of San Diego School of Law,NaN,2013-12-12 14:38:33,2013-12-12 14:38:33,Edward J. Treska,480761,480761,c:39172,NaN,NaN,0,273050,"""Senior Vice President General Counsel of Acac...",2013-12-12 11:37:18,2013-12-12 11:37:18
390906,226655,p:268528,Edward,J. Treska,NaN,Unaffiliated,109610,J.D.,NaN,University of San Diego School of Law,NaN,2013-12-12 14:38:33,2013-12-12 14:38:33,Edward J. Treska,480907,480907,c:286152,NaN,NaN,1,273049,Vice President,2013-12-12 14:39:36,2013-12-12 14:39:36
390907,226655,p:268528,Edward,J. Treska,NaN,Unaffiliated,109610,J.D.,NaN,University of San Diego School of Law,NaN,2013-12-12 14:38:33,2013-12-12 14:38:33,Edward J. Treska,480908,480908,c:286220,NaN,NaN,1,1,"General Counsel, Director of Patents and Licen...",2013-12-12 14:39:48,2013-12-12 14:39:48
390908,226655,p:268528,Edward,J. Treska,NaN,Unaffiliated,109610,J.D.,NaN,University of San Diego School of Law,NaN,2013-12-12 14:38:33,2013-12-12 14:38:33,Edward J. Treska,480909,480909,c:286221,NaN,NaN,1,1,Design Engineer,2013-12-12 14:40:04,2013-12-12 14:40:04
390909,226687,p:268560,Drew,Langloh,NaN,Unaffiliated,109575,MBA,NaN,Samford University,2008-01-01,2013-12-12 11:52:31,2013-12-12 11:52:31,Drew Langloh,480795,480795,c:286096,NaN,NaN,0,1,President and CEO,2013-12-12 11:50:37,2013-12-12 11:50:37
390910,226705,p:268589,John,Pins,NaN,Unaffiliated,109605,B.S.,Accounting,Iowa State University,NaN,2013-12-12 14:28:58,2013-12-12 14:28:58,John Pins,480894,480894,c:12612,2006-06-01,NaN,0,4,"VP, Finance & Clinical Solutions",2013-12-12 14:26:05,2013-12-12 14:33:20
390911,226705,p:268589,John,Pins,NaN,Unaffiliated,109605,B.S.,Accounting,Iowa State University,NaN,2013-12-12 14:28:58,2013-12-12 14:28:58,John Pins,480898,480898,c:12612,NaN,NaN,1,2,Accounting Manager for Facts & Comparisons,2013-12-12 14:33:21,2013-12-12 14:33:21
390912,226705,p:268589,John,Pins,NaN,Unaffiliated,109605,B.S.,Accounting,Iowa State University,NaN,2013-12-12 14:28:58,2013-12-12 14:28:58,John Pins,480899,480899,c:12612,NaN,NaN,1,3,"Controller, Wolters Kluwer Health",2013-12-12 14:33:21,2013-12-12 14:33:21
390913,226705,p:268589,John,Pins,NaN,Unaffiliated,109605,B.S.,Accounting,Iowa State University,NaN,2013-12-12 14:28:58,2013-12-12 14:28:58,John Pins,480900,480900,c:12612,1997-01-01,NaN,1,1,"Director, Accounting - Professional & Educatio...",2013-12-12 14:33:21,2013-12-12 14:33:21
390914,226705,p:268589,John,Pins,NaN,Unaffiliated,109606,CPA,NaN,American Institute of Certtified Public Accoun...,NaN,2013-12-12 14:28:58,2013-12-12 14:28:58,John Pins,480894,480894,c:12612,2006-06-01,NaN,0,4,"VP, Finance & Clinical Solutions",2013-12-12 14:26:05,2013-12-12 14:33:20
390915,226705,p:268589,John,Pins,NaN,Unaffiliated,109606,CPA,NaN,American Institute of Certtified Public Accoun...,NaN,2013-12-12 14:28:58,2013-12-12 14:28:58,John Pins,480898,480898,c:12612,NaN,NaN,1,2,Accounting Manager for Facts & Comparisons,2013-12-12 14:33:21,2013-12-12 14:33:21
390916,226705,p:268589,John,Pins,NaN,Unaffiliated,109606,CPA,NaN,American Institute of Certtified Public Accoun...,NaN,2013-12-12 14:28:58,2013-12-12 14:28:58,John Pins,480899,480899,c:12612,NaN,NaN,1,3,"Controller, Wolters Kluwer Health",2013-12-12 14:33:21,2013-12-12 14:33:21
390917,226705,p:268589,John,Pins,NaN,Unaffiliated,109606,CPA,NaN,American Institute of Certtified Public Accoun...,NaN,2013-12-12 14:28:58,2013-12-12 14:28:58,John Pins,480900,480900,c:12612,1997-01-01,NaN,1,1,"Director, Accounting - Professional & Educatio...",2013-12-12 14:33:21,2013-12-12 14:33:21

In [53]:
def keep_only_needed_info(df_tmp, list_columns):
    for element in list(df_tmp.columns):
        if element not in list_columns:
            print(element)
            df_tmp.drop([element], axis=1)

In [54]:
keep_only_needed_info(df_people, people_needed_info)

id_x
first_name
last_name
birthplace
affiliation_name
id_y
degree_type
institution
graduated_at
created_at_x
updated_at_x
id
relationship_id
start_at
end_at
is_past
sequence
title
created_at_y
updated_at_y

In [55]:
people_needed_info

['full_name', 'subject', 'object_id', 'relationship_object_id']

In [56]:
df_people_needed_info = df_people[people_needed_info]
df_people_needed_info

,full_name,subject,object_id,relationship_object_id
0,Ben Elowitz,Electrical Engineering/Computer Science,p:2,c:1
1,Ben Elowitz,Electrical Engineering/Computer Science,p:2,c:4993
2,Ben Elowitz,Electrical Engineering/Computer Science,p:2,c:233024
3,Ben Elowitz,Electrical Engineering/Computer Science,p:2,f:1017
4,Ben Elowitz,Electrical Engineering/Computer Science,p:2,c:18661
5,Ben Elowitz,Electrical Engineering/Computer Science,p:2,c:537
6,Ben Elowitz,Electrical Engineering/Computer Science,p:2,c:2361
7,Ben Elowitz,Electrical Engineering/Computer Science,p:2,c:268504
8,Ben Elowitz,Applied Mathematics,p:2,c:1
9,Ben Elowitz,Applied Mathematics,p:2,c:4993
10,Ben Elowitz,Applied Mathematics,p:2,c:233024
11,Ben Elowitz,Applied Mathematics,p:2,f:1017
12,Ben Elowitz,Applied Mathematics,p:2,c:18661
13,Ben Elowitz,Applied Mathematics,p:2,c:537
14,Ben Elowitz,Applied Mathematics,p:2,c:2361
15,Ben Elowitz,Applied Mathematics,p:2,c:268504
16,Kevin Flaherty,NaN,p:3,c:1
17,Kevin Flaherty,NaN,p:3,f:1017
18,Kevin Flaherty,NaN,p:3,c:28294
19,Kevin Flaherty,NaN,p:3,c:45209
20,Kevin Flaherty,NaN,p:3,c:60421
21,Kevin Flaherty,NaN,p:3,c:174210
22,Kevin Flaherty,NaN,p:3,c:220488
23,Kevin Flaherty,NaN,p:3,c:196560
24,Kevin Flaherty,NaN,p:3,c:200709
25,Kevin Flaherty,NaN,p:3,c:220489
26,Kevin Flaherty,NaN,p:3,f:1017
27,Kevin Flaherty,NaN,p:3,c:1
28,Kevin Flaherty,NaN,p:3,f:1017
29,Kevin Flaherty,NaN,p:3,c:28294
...,...,...,...,...
390888,James Trueman,Business Administration,p:268524,c:286211
390889,James Trueman,Business Administration,p:268524,c:286212
390890,James Trueman,Business Administration,p:268524,c:4715
390891,James Trueman,Business Administration,p:268524,c:4715
390892,James Trueman,Business Administration,p:268524,c:286213
390893,Harry Wei,Engineering,p:268527,c:39172
390894,Harry Wei,Engineering,p:268527,c:39172
390895,Harry Wei,Engineering,p:268527,c:286217
390896,Harry Wei,Engineering,p:268527,c:286218
390897,Harry Wei,Engineering,p:268527,c:39172
390898,Harry Wei,Engineering,p:268527,c:39172
390899,Harry Wei,Engineering,p:268527,c:286217
390900,Harry Wei,Engineering,p:268527,c:286218
390901,Edward J. Treska,Electrical Engineering,p:268528,c:39172
390902,Edward J. Treska,Electrical Engineering,p:268528,c:286152
390903,Edward J. Treska,Electrical Engineering,p:268528,c:286220
390904,Edward J. Treska,Electrical Engineering,p:268528,c:286221
390905,Edward J. Treska,NaN,p:268528,c:39172
390906,Edward J. Treska,NaN,p:268528,c:286152
390907,Edward J. Treska,NaN,p:268528,c:286220
390908,Edward J. Treska,NaN,p:268528,c:286221
390909,Drew Langloh,NaN,p:268560,c:286096
390910,John Pins,Accounting,p:268589,c:12612
390911,John Pins,Accounting,p:268589,c:12612
390912,John Pins,Accounting,p:268589,c:12612
390913,John Pins,Accounting,p:268589,c:12612
390914,John Pins,NaN,p:268589,c:12612
390915,John Pins,NaN,p:268589,c:12612
390916,John Pins,NaN,p:268589,c:12612
390917,John Pins,NaN,p:268589,c:12612

In [59]:
df_people_needed_info.to_csv('people_info.csv')